// Vocabulário jogável do Wordmila
// Categorias: parentesco, cores, profissões, corpo, objetos, países + verbos conjugados
// Limite do jogo: 3 a 12 letras (sem acento) — cobre adjetivos comuns e plurais (TRABALHADORA, INTELIGENTE…)

function stripAccents(s) {
    return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase();
}

function okWord(w) {
    return /^[A-Z]+$/.test(w) && w.length >= 3 && w.length <= 12;
}

// ========== PARENTESCO ==========
const WORDS_FAMILY = [
    'PAI','MAE','FILHO','FILHA','IRMAO','IRMA','TIO','TIA','AVO','AVO',
    'NETO','NETA','NETOS','NETAS','PRIMO','PRIMA','PRIMOS','PRIMAS',
    'SOBRINHO','SOBRINHA','MARIDO','ESPOSA','ESPOSO','CASAL','FAMILIA',
    'PARENTE','PARENTES','NOIVO','NOIVA','NAMORADO','NAMORADA',
    'PADRASTO','MADRASTA','ENTEADO','ENTEADA','CUNHADO','CUNHADA',
    'SOGRO','SOGRA','GENRO','NORA','PADRINHO','MADRINHA',
    'AFILHADO','AFILHADA','BISAVO','BISNETO','BISNETA','TATARAVO',
    'VIUVO','VIUVA','ORFAO','ORFA','GEMEO','GEMEA','GEMEOS',
    'MEIOIRMAO','MEIAIRMA','CONCUADO','CONCUADA','COMPADRE','COMADE',
    'PATRIARCA','MATRIARCA','ANCESTRAL','DESCENDENTE','HERDEIRO','HERDEIRA',
    'BEBE','CRIANCA','MENINO','MENINA','JOVEM','ADULTO','IDOSO','ANCIAO',
    'HOMEM','MULHER','SENHOR','SENHORA','DONA','DONO','CASADO','CASADA',
    'SOLTEIRO','SOLTEIRA','DIVORCIADO','DIVORCIADA','NOIVADO','CASAMENTO'
];

// ========== CORES ==========
const WORDS_COLORS = [
    'AZUL','VERDE','VERMELHO','VERMELHA','AMARELO','AMARELA','PRETO','PRETA',
    'BRANCO','BRANCA','CINZA','ROSA','ROXO','ROXA','MARROM','LARANJA',
    'BEGE','DOURADO','DOURADA','PRATEADO','PRATEADA','LILAS','VIOLETA',
    'INDIGO','CIANO','MAGENTA','TURQUESA','CORAL','SALMAO','CREME','MARFIM',
    'OURO','PRATA','VINHO','CARMESIM','EBANO','CAQUI','MOSTARD','JADE',
    'ANIL','CEREJA','CHOCOLATE','FERRUGEM','ESMERALDA','RUBI','SAFIRA',
    'PETROLEO','AZEITONA','GELO','NEVE','NOZ','AREIA','BARRO','COBRE',
    'BRONZE','CHUMBO','GRAFITE','CARVAO','FUMAÇA','FUMACA','LAVANDA',
    'MENTA','AQUA','NAVY','PINK','GOLD','SILVER','BLACK','WHITE',
    'CLARO','CLARA','ESCURO','ESCURA','OPACO','OPACA','BRILHANTE','FOSCO',
    'COLORIDO','COLORIDA','PINTADO','PINTADA','TINTA','PIGMENTO','TOM','COR',
    'CORES','MATIZ','NUANCE','PASTEL','NEON','METALICO','METALICA'
];

// ========== PROFISSÕES ==========
const WORDS_JOBS = [
    'MEDICO','MEDICA','DOUTOR','DOUTORA','DENTISTA','ENFERMEIRO','ENFERMEIRA',
    'CIRURGIAO','PEDIATRA','PSICOLOGO','PSIQUIATRA','FARMACEUTICO','VETERINARIO',
    'PROFESSOR','PROFESSORA','MESTRE','MESTRA','ALUNO','ALUNA','DIRETOR','DIRETORA',
    'COORDENADOR','SECRETARIO','SECRETARIA','BIBLIOTECARIO','PESQUISADOR',
    'ENGENHEIRO','ENGENHEIRA','ARQUITETO','ARQUITETA','ADVOGADO','ADVOGADA',
    'JUIZ','JUÍZA','JUIZA','PROMOTOR','PROMOTORA','DELEGADO','DELEGADA',
    'POLICIAL','BOMBEIRO','BOMBEIRA','SOLDADO','MILITAR','MARINHEIRO','PILOTO',
    'MOTORISTA','CAMINHONEIRO','TAXISTA','COBRADOR','MECANICO','MECANICA',
    'ELETRICISTA','PEDREIRO','PINTOR','PINTORA','CARPINTEIRO','SERRALHEIRO',
    'ENCANADOR','SOLDADOR','MARCENEIRO','JARDINEIRO','FAXINEIRO','FAXINEIRA',
    'COZINHEIRO','COZINHEIRA','GARCOM','GARCONETE','CHEFE','CONFEITEIRO',
    'PADEIRO','PADEIRA','ACOUGUEIRO','PEIXEIRO','VENDEDOR','VENDEDORA',
    'CAIXA','GERENTE','ATENDENTE','RECEPCIONISTA','BALCONISTA','PROMOTOR',
    'CONTADOR','CONTADORA','ECONOMISTA','BANCARIO','BANCARIA','AUDITOR',
    'PROGRAMADOR','PROGRAMADORA','ANALISTA','DESIGNER','ARTISTA','MUSICO',
    'MUSICA','CANTOR','CANTORA','ATOR','ATRIZ','DANCARINO','DANCARINA',
    'ESCRITOR','ESCRITORA','JORNALISTA','REPORTER','FOTOGRAFO','FOTOGRAFA',
    'CINEASTA','DIRETOR','PRODUTOR','PRODUTORA','EDITOR','EDITORA',
    'EMPRESARIO','EMPRESARIA','COMERCIANTE','SACOLEIRA','FEIRANTE','AMBULANTE',
    'AGRICULTOR','AGRICULTORA','PESCADOR','PESCADORA','VAQUEIRO','PEAO',
    'FAZENDEIRO','SITIANTE','CASEIRO','CASEIRA','PORTEIRO','PORTEIRA',
    'SEGURANCA','VIGIA','GUARDA','DETEIVE','DETEIVE','INVESTIGADOR',
    'CIENTISTA','BIOLOGO','BIOLOGA','QUIMICO','QUIMICA','FISICO','FISICA',
    'MATEMATICO','HISTORIADOR','GEOGRAFO','ASTRONOMO','GEOLOGO',
    'PADRE','PASTOR','PASTORA','FREIRA','MONGE','BISPO','PAPA','RABINO',
    'POLITICO','POLITICA','DEPUTADO','DEPUTADA','SENADOR','SENADORA',
    'PREFEITO','PREFEITA','VEREADOR','VEREADORA','GOVERNADOR','PRESIDENTE',
    'MINISTRO','MINISTRA','EMBAIXADOR','CONSUL','DIPLOMATA','SERVIDOR',
    'FUNCIONARIO','FUNCIONARIA','ESTAGIARIO','ESTAGIARIA','APRENDIZ','CHEFE',
    'DONO','DONA','PATRAO','PATROA','SOCIO','SOCIA','CLIENTE','PACIENTE',
    'BARBEIRO','CABELEIREIRO','MANICURE','ESTETICISTA','MASSAGISTA','PERSONAL',
    'TECNICO','TECNICA','OPERADOR','OPERADORA','AUXILIAR','ASSISTENTE',
    'TRADUTOR','TRADUTORA','INTERPRETE','GUIA','TURISMO','HOTELEIRO',
    'PIZZAIOLO','SORVETEIRO','CHURRASQUEIRO','BARTENDER','BARMAN','DJ'
];

// ========== PARTES DO CORPO ==========
const WORDS_BODY = [
    'CABECA','ROSTO','CARA','TESTA','SOBRANCELHA','CILIO','OLHO','OLHOS',
    'PUPILA','IRIS','NARIZ','NARINA','BOCA','LABIO','LABIOS','DENTE','DENTES',
    'GENGIVA','LINGUA','CEU','PALATO','QUEIXO','MANDIBULA','MAXILAR','BOCHECHA',
    'ORELHA','TIMPANO','PESCOCO','GARGANTA','NUCA','OMBRO','OMBROS','CLAVICULA',
    'BRACO','BRACOS','COTOVELO','ANTEBRACO','PULSO','MAO','MAOS','PALMA',
    'DEDO','DEDOS','POLEGAR','INDICADOR','MEDIO','ANELAR','MINIMO','UNHA','UNHAS',
    'PEITO','SEIO','SEIOS','TORAX','COSTELA','COSTELAS','COSTAS','COLUNA',
    'VERTEBRA','COLUNA','LOMBAR','CINTURA','QUADRIL','BARRIGA','ABDOMEN',
    'UMBIGO','VIRILHA','PERNA','PERNAS','COXA','COXAS','JOELHO','JOELHOS',
    'CANELA','TORNOZELO','PE','PES','CALCANHAR','PLANTA','DEDÃO','DEDAO',
    'CORACAO','PULMAO','PULMOES','FIGADO','RIM','RINS','ESTOMAGO','INTESTINO',
    'PANCREAS','BACO','VESICULA','BEIXIGA','BEXIGA','UTERO','OVARIO','PROSTATA',
    'SANGUE','VEIA','VEIAS','ARTERIA','NERVO','NERVOS','MUSCULO','MUSCULOS',
    'OSSO','OSSOS','CARTILAGEM','TENDÃO','TENDAO','LIGAMENTO','PELE','PORO',
    'CABELO','CABELOS','FIO','FIOS','BARBA','BIGODE','SOBRANCELHAS','CILIOS',
    'SUOR','LAGRIMA','LAGRIMAS','SALIVA','MUCO','GORDURA','TECIDO','CELULA',
    'ORGAO','ORGAOS','MEMBRO','MEMBROS','CORPO','TRONCO','MEMBRANA','PELE'
];

// ========== OBJETOS DO COTIDIANO ==========
const WORDS_OBJECTS = [
    // casa
    'CASA','PORTA','JANELA','PAREDE','CHAO','TETO','TELHADO','ESCADA','CORREDOR',
    'SALA','QUARTO','BANHO','COZINHA','VARANDA','GARAGEM','JARDIM','QUINTAL',
    'CAMA','MESA','CADEIRA','SOFA','POLTRONA','BANCO','ESTANTE','ARMA','ARIO',
    'ARMARIO','GUARDA','ROUPA','GAVETA','PRATELEIRA','CABIDE','ESPETHO','ESPELHO',
    'LAMPADA','LUSTRE','ABAJUR','INTERRUPTOR','TOMADA','FIO','EXTENSAO','FILTRO',
    'GELADEIRA','FOGAO','FORNO','MICROONDAS','LIQUIDIFICADOR','BATEDEIRA','PANELA',
    'FRIGIDEIRA','CHALEIRA','CAFETEIRA','TORRADEIRA','AIRFRYER','FREEZER','PIA',
    'TORNEIRA','RALO','VASO','VASO','DESCARGADOR','BOX','CHUVEIRO','TOALHA',
    'SABONETE','SHAMPOO','CONDICIONADOR','ESCOVA','PENTE','SECADOR','BARBEADOR',
    'PAPEL','HIGIENICO','PASTADENTE','ESCOVADENTE','FIO','DENTAL','CORTINA',
    'PERSIANA','TAPETE','ALMOFADA','TRAVESSEIRO','COBERTOR','LENCOL','EDREDOM',
    'TRAVESSA','PRATO','COPO','XICARA','CANECA','GARFO','FACA','COLHER','CONCHA',
    'TABUA','ROLO','RALADOR','ABRIDOR','SACA','ROLHA','GARRAFA','POTE','TIGELA',
    'TUPPER','POTE','LIXEIRA','VASSOURA','RODO','PANO','ESPONJA','DETERGENTE',
    'SABAO','AMACIANTE','ALVEJANTE','BALDE','ASPIRADOR','FERRO','TABUA',
    // roupa / acessórios
    'CAMISA','CAMISETA','BLUSA','CALCA','SHORT','BERMUDA','SAIA','VESTIDO',
    'CASACO','JAQUETA','MOLETOM','CASACO','COLETE','GRAVATA','CINTO','MEIA',
    'CUECA','CALCINHA','SUTIA','PIJAMA','ROUPAO','TENIS','SAPATO','CHINELO',
    'SANDALIA','BOTA','BONE','CHAPEU','GORRO','OCULOS','RELOGIO','ANEL',
    'BRINCO','CORDAO','PULSEIRA','COLAR','BROCHE','BOLSA','MOCHILA','CARTEIRA',
    'CHAVE','CHAVEIRO','GUARDA','CHUVA','LENCO','CACHECOL','LUVA','MEIAO',
    // tecnologia / escritório
    'CELULAR','TELEFONE','TABLET','NOTEBOOK','COMPUTADOR','TECLADO','MOUSE',
    'TELA','MONITOR','IMPRESSORA','SCANNER','CABO','CARREGADOR','FONE','CAIXA',
    'SOM','RADIO','TV','CONTROLE','DVD','PENDRIVE','HD','SSD','ROTEADOR',
    'MODEM','CAMERA','FILMADORA','DRONE','CONSOLE','JOYSTICK','CONTROLE',
    'LIVRO','CADERNO','LAPIS','CANETA','BORRACHA','APONTADOR','RÉGUA','REGUA',
    'ESTOJO','PASTA','CLIP','GRAMPEADOR','FITA','COLA','TESOURA','PAPEL',
    'CARTOLINA','SULFITE','ENVELOPE','SELO','CARIMBO','AGENDA','CALENDARIO',
    // transporte / rua
    'CARRO','MOTO','BICICLETA','PATINETE','SKATE','PATINS','TREM','METRO',
    'ONIBUS','CAMINHAO','VAN','TAXI','AVIAO','HELICOPTERO','BARCO','NAVIO',
    'CANOA','JETSKI','CAPACETE','CINTO','VOLANTE','PEDAL','RODA','PNEU',
    'FAROL','SETA','BUZINA','RETROVISOR','PORTA','MALA','PORTA','MALAS',
    // lazer / outros
    'BOLA','BONECA','URSO','CARRINHO','QUEBRA','CABECA','DADO','CARTA','BARALHO',
    'XADREZ','DAMAS','DOMINO','VIDEOGAME','BRINQUEDO','PIAO','IOIO','PIPA',
    'VIOLAO','GUITARRA','PIANO','TECLADO','BATERIA','FLAUTA','VIOLINO','MICROFONE',
    'CAIXA','SOM','FONE','ALTO','FALANTE','PROJETOR','TELA','QUADRO','MOLDURA',
    'VASO','PLANTA','FLOREIRA','RELOGIO','QUADRO','ESPELHO','LUMINARIA','ABAJUR',
    'VENTILADOR','AR','CONDICIONADO','AQUECEDOR','UMIDIFICADOR','PURIFICADOR',
    'LANTERNA','PILHA','BATERIA','ISQUEIRO','FOSFORO','VELA','INCENSO','PERFUME',
    'MAQUIAGEM','BATON','BASE','RIMEL','SOMBRA','ESMALTE','ALICATE','TESOURA',
    'AGULHA','LINHA','BOTAO','ZÍPER','ZIPER','ALFINETE','COSTURA','TECIDO',
    'MOEDA','NOTA','CARTAO','DINHEIRO','COFRE','PORQUINHO','CARTEIRA','BOLSO',
    // ferramentas / madeira / objetos extras
    'PAU','PAUS','MADEIRA','TRONCO','GALHO','VARA','BASTAO','TACO','CACETE',
    'MARTELO','SERROTE','SERRA','ALICATE','PARAFUSO','PORCA','ARRUELA','PREGO',
    'PINO','GRAMPO','LIXA','LIMA','FORMAO','PLAINA','NIVEL','TRENA','ESQUADRO',
    'COMPASSO','FURADEIRA','MACHADO','FOICE','ENXADA','ANCINHO','REGADOR',
    'MANGUEIRA','SACOLA','SACO','EMBALAGEM','PAPELAO','PLASTICO','VIDRO','LATA',
    'TAMPA','ROLHA','TAMPINHA','LACRE','ETIQUETA','ADESIVO','CORDA','BARBANTE',
    'ELASTICO','PRENDEDOR','ESTILETE','CARIMBO','PACOTE','LENHA','TOCO','CEPO'
];

// ========== PAÍSES (até 8 letras após tirar acento) ==========
const WORDS_COUNTRIES = [
    // Américas
    'BRASIL','CHILE','PERU','CUBA','HAITI','MEXICO','CANADA','PANAMA','BELIZE',
    'HONDURAS','EQUADOR','BOLIVIA','URUGUAI','PARAGUAI','COLOMBIA','SURINAME',
    'GUIANA','JAMAICA','BAHAMAS','BARBADOS','GRENADA','DOMINICA','ARUBA',
    'CURACAO','EUA','USA','ARGENTINA','VENEZUELA','NICARAGUA','GUATEMALA',
    'EL','SALVADOR','COSTARICA','PUERTORICO','MARTINICA','GUADALUPE',
    // Europa
    'PORTUGAL','ESPANHA','FRANCA','ITALIA','ALEMANHA','HOLANDA','BELGICA',
    'SUECIA','NORUEGA','POLONIA','GRECIA','TURQUIA','RUSSIA','UCRANIA',
    'ROMENIA','SERVIA','CROACIA','BOSNIA','ALBANIA','KOSOVO','BULGARIA',
    'HUNGRIA','AUSTRIA','SUICA','IRLANDA','ESCOCIA','DINAMARCA','FINLANDIA',
    'ISLANDIA','MALTA','CHIPRE','ANDORRA','MONACO','LIECHTENSTEIN','LUXEMBURGO',
    'ESLOVAQUIA','ESLOVENIA','ESTONIA','LETONIA','LITUANIA','MOLDAVIA','BELARUS',
    'GEORGIA','ARMENIA','AZERBAIJAO','INGLATERRA','GALES','PAISESBAIXOS',
    // África
    'ANGOLA','NIGERIA','QUENIA','GANA','MALI','TOGO','BENIM','CONGO','RUANDA',
    'UGANDA','ETIOPIA','SOMALIA','SUDAO','LIBIA','TUNISIA','ARGELIA','MARROCOS',
    'EGITO','SENEGAL','CAMAROES','GABAO','CHADE','NIGER','ZAMBIA','MALAWI',
    'ZIMBABUE','BOTSWANA','NAMIBIA','LESOTO','SUAZILANDIA','MOCAMBIQUE','GUINE',
    'LIBERIA','SERRA','LEOA','GAMBIA','BURUNDI','ERITREIA','DJIBUTI','COMORES',
    'MAURICIO','SEYCHELES','CABOVERDE','SAOTOME','SUDAFRICA','MADAGASCAR',
    // Ásia / Oriente Médio
    'CHINA','JAPAO','INDIA','NEPAL','LAOS','IRAQUE','IRA','OMA','CATAR','IEMEN',
    'ISRAEL','LIBANO','SIRIA','JORDANIA','KUWAIT','BAHREIN','EMIRADOS','ARABIA',
    'PAQUISTAO','AFEGANISTAO','BANGLADESH','BIRMANIA','TAILANDIA','MALASIA',
    'VIETNA','COREIA','MONGOLIA','CAZAQUISTAO','UZBEQUISTAO','TAJIQUISTAO',
    'QUIRGUISTAO','TURCOMENISTAO','GEORGIA','ARMENIA','CINGAPURA','FILIPINAS',
    'INDONESIA','BRUNEI','BUTAO','MALDIVAS','SRI','LANKA','CAMBOJA','TIMOR',
    // Oceania
    'AUSTRALIA','FIJI','SAMOA','TONGA','PALAU','NAURU','TUVALU','VANUATU',
    'KIRIBATI','NOVAZELANDIA','PAPUA','MICRONESIA','POLINESIA',
    // outros / regiões comuns
    'VATICANO','TAIWAN','TIBETE','ESCOCIA','CATALUNHA','BASQUE','GALIZA'
];

// ========== CARACTERÍSTICAS HUMANAS ==========
const WORDS_TRAITS = [
    // pele / marcas
    'SARDA','SARDAS','SARDENTO','SARDENTA','PINTA','PINTAS','MANCHA','MANCHAS',
    'CICATRIZ','VERRUGA','ESPINHA','CRAVO','RUGAS','RUGA','PELE','ALBINO','ALBINA',
    'MORENO','MORENA','BRANCO','BRANCA','NEGRO','NEGRA','PARDO','PARDA','CLARO','CLARA',
    'ESCURO','ESCURA','QUEIMADO','QUEIMADA','BRONZEADO','BRONZEADA','PALIDO','PALIDA',
    // cabelo
    'CABELO','CABELOS','CACHEADO','CACHEADA','LISO','LISA','CRESPO','CRESPA',
    'ONDULADO','ONDULADA','RUIVO','RUIVA','LOIRO','LOIRA','CASTANHO','CASTANHA',
    'PRETO','PRETA','GRISALHO','GRISALHA','CALVO','CALVA','CARECA','FRANJA',
    'TRANCA','TRANCAS','RABO','COQUE','TOPETE','BARBA','BIGODE','COSTELETA',
    // corpo / biotipo
    'ALTO','ALTA','BAIXO','BAIXA','GORDO','GORDA','MAGRO','MAGRA','FORTE','FORTE',
    'FRACO','FRACA','ATLETICO','ATLETICA','MUSCULOSO','MUSCULOSA','ESBELTO','ESBELTA',
    'ROBUSTO','ROBUSTA','DELGADO','DELGADA','ANAO','ANA','GIGANTE','GRANDE','PEQUENO','PEQUENA',
    'GORDO','GORDA','CHEIO','CHEIA','SECAR','SECO','SECA','VOLUMOSO','VOLUMOSA',
    // rosto / traços
    'BONITO','BONITA','LINDO','LINDA','FEIO','FEIA','FOFO','FOFA','BELO','BELA',
    'SIMPATICO','SIMPATICA','CHARMOSO','CHARMOSA','ELEGANTE','GRACIOSO','GRACIOSA',
    'OLHOS','OLHO','AZUL','VERDE','CASTANHO','PRETO','PUXADO','PUXADA','RASGADO','RASGADA',
    'NARIZ','FINO','FINA','GROSSO','GROSSA','BOCA','GRANDE','PEQUENA','DENTE','DENTES',
    'SOBRANCELHA','GROSSA','FINA','ORELHA','GRANDE','PEQUENA','QUEIXO','TESTA',
    // personalidade
    'ALEGRE','TRISTE','CALMO','CALMA','NERVOSO','NERVOSA','BRAVO','BRAVA','DOCE',
    'AMAVEL','GENTIL','EDUCADO','EDUCADA','GROSSEIRO','GROSSEIRA','EDUCADA',
    'TIMIDO','TIMIDA','EXTROVERTIDO','EXTROVERTIDA','INTROVERTIDO','INTROVERTIDA',
    'INTELIGENTE','ESPERTO','ESPERTA','BURRO','BURRA','SABIO','SABIA','GENIO',
    'CRIATIVO','CRIATIVA','CURIOSO','CURIOSA','ATENTO','ATENTA','DISTRAIDO','DISTRAIDA',
    'PACIENTE','IMPACIENTE','GENEROSO','GENEROSA','EGOISTA','CIUMENTO','CIUMENTA',
    'FIEL','TRAIDOR','TRAIDORA','HONESTO','HONESTA','MENTIROSO','MENTIROSA',
    'CORAJOSO','CORAJOSA','COVARDE','MEDROSO','MEDROSA','AUDAZ','OUSADO','OUSADA',
    'TRANQUILO','TRANQUILA','ANSIOSO','ANSIOSA','ESTRESSADO','ESTRESSADA','CANSADO','CANSADA',
    'ANIMADO','ANIMADA','ENTUSIASMADO','ENTUSIASMADA','MOTIVADO','MOTIVADA',
    'PREGUICOSO','PREGUICOSA','TRABALHADOR','TRABALHADORA','DEDICADO','DEDICADA',
    'ORGANIZADO','ORGANIZADA','DESORGANIZADO','DESORGANIZADA','LIMPO','LIMPA','SUJO','SUJA',
    'SAUDAVEL','DOENTE','FORTE','FRACO','FRACA','ATIVADO','ATIVA','SEDENTARIO','SEDENTARIA',
    'JOVEM','VELHO','VELHA','MADURO','MADURA','IMATURO','IMATURA','ADULTO','ADULTA',
    'CRIANCA','BEBE','ADOLESCENTE','IDOSO','IDOSA','ANCIAO','ANCIA',
    'RICO','RICA','POBRE','MODESTO','MODESTA','HUMILDE','ORGULHOSO','ORGULHOSA',
    'FELIZ','INFELIZ','SORTUDO','SORTUDA','AZARADO','AZARADA','OTIMISTA','PESSIMISTA',
    'ROMANTICO','ROMANTICA','CARINHOSO','CARINHOSA','FRIO','FRIA','QUENTE',
    'DIVERTIDO','DIVERTIDA','CHATOS','CHATO','CHATA','ENGRAÇADO','ENGRACADO','ENGRACADA',
    'SERIO','SERIA','BRINCALHAO','BRINCALHONA','BAGUNCEIRO','BAGUNCEIRA',
    'RESPONSAVEL','IRRESPONSAVEL','PONTUAL','ATRASADO','ATRASADA','LENTO','LENTA','RAPIDO','RAPIDA',
    'HABILIDOSO','HABILIDOSA','DESAJEITADO','DESAJEITADA','AGIL','LENTO','LENTA',
    'CEGO','CEGA','SURDO','SURDA','MUDO','MUDA','PARALITICO','PARALITICA',
    'CANHOTO','CANHOTA','DESTRO','DESTRA','BILINGUE','ANALFABETO','ANALFABETA',
    'LOIRO','LOIRA','MORENO','MORENA','RUIVO','RUIVA','SARDA','SARDAS','SARDENTO','SARDENTA'
];

// ========== ANIMAIS E INSETOS ==========
const WORDS_ANIMALS = [
    // domésticos / comuns
    'GATO','GATA','GATOS','GATAS','GATINHO','GATINHA','CAO','CAES','CACHORRO','CACHORRA',
    'CACHORRINHO','CACHORRINHA','PASSARO','PASSARA','PEIXE','PEIXES','HAMSTER','COELHO','COELHA',
    'PORQUINHO','PORQUINHA','TARTARUGA','PATO','PATA','PATOS','PATAS','GALINHA','GALO',
    'PINTINHO','PINTINHA','PERU','PATO','GANSO','GANSA','CODORNA','POMBO','POMBA',
    'PAPAGAIO','CANARIO','CANARIA','CALOPSITA','PERIQUITO','BEMTEVI','SABIÁ','SABIA',
    // fazenda
    'VACA','BOI','TOURO','BEZERRO','BEZERRA','CAVALO','EGUA','POTRO','POTRA','BURRO','BURRA',
    'JUMENTO','JUMENTA','PORCO','PORCA','LEITAO','LEITOA','OVELHA','CARNEIRO','CORDEIRO','CORDEIRA',
    'CABRA','BODE','CABRITO','CABRITA','BUFALO','BUFALA','LHAMA','ALPACA',
    // selvagens
    'LEAO','LEOA','TIGRE','TIGRESA','ONCA','JAGUAR','PUMA','LINCE','LOBO','LOBA',
    'RAPOSA','URSO','URSA','URSO','PANDA','KOALA','CANGURU','MACACO','MACACA','GORILA',
    'CHIPANZE','ORANGOTANGO','LEMURE','PREGUICA','TAMANDUA','TATU','CAPIVARA','ANTAS',
    'ANTA','VEADO','CERVO','CORCA','ALCE','RENA','ELEFANTE','RINOCERONTE','HIPOPOTAMO',
    'GIRAFA','ZEBRA','HIPOPOTAMO','CAMELLO','CAMELO','DROMEDARIO','BUFFALO',
    'JACARE','CROCODILO','LAGARTO','IGUANA','CAMALEAO','COBRA','SERPENTE','VIPERA',
    'JARARACA','SUCURI','PITON','COBRA','SAPO','SA','RA','RA','PERERECA','SALAMANDRA',
    'TUBARAO','BALEIA','GOLFINHO','ORCA','FOCA','LEAO','MARINHO','PEIXEBOI','ARRAIA',
    'POLVO','LULA','AGUA','VIVA','ESTRELA','DO','MAR','CARANGUEJO','CAMARAO','LAGOSTA',
    'OURIÇO','OURICO','MORCEGO','RATO','RATA','RATAZANA','ESQUILO','PORCO','ESPINHO',
    'TEXUGO','DONINHA','FURAO','LONTRA','CASTOR','TOUPEIRA','OURIÇO',
    // aves
    'AGUIA','FALCAO','GAVIÃO','GAVIAO','CORUJA','MOCHO','URUBU','CONDOR','PELICANO',
    'GAIVOTA','PATO','CISNE','FLAMINGO','TUCANO','ARARA','ARARINHA','PAPAGAIO','BEMTEVI',
    'ROLINHA','POMBO','ANDORINHA','BEIja','FLOR','BEIjaFLOR','BEIja','COLIBRI','PICA','PAU',
    'PICA','PAU','AVESTRUZ','EMA','PENGUIM','PENGÜIM','PENGUIM','PELICANO',
    // insetos / artrópodes
    'FORMIGA','FORMIGAS','ABELHA','ABELHAS','VESPA','MARIMBONDO','BORBOLETA','MARIPOSA',
    'MOSCA','MOSQUITO','PERNILONGO','BARATA','BARATAS','GRILO','GAFANHOTO','CIGARRA',
    'JOANINHA','BESOURO','VAGA','LUME','VAGALUME','LIBELULA','LOUVA','DEUS','LOUVADEUS',
    'PULGA','PIOLHO','CARRAPATO','ÁCARO','ACARO','ARANHA','ARANHAS','ESCORPIAO',
    'CENTOPEIA','LACRAIA','CARANGUEJEIRA','OPILIAO','MINHOCA','LESMA','CARACOL',
    'BESOURO','PERCEVEJO','CUPIM','TRAÇA','TRACA','MARIPOSA','PULGAO',
    // outros
    'ANIMAL','ANIMAIS','BICHO','BICHOS','INSETO','INSETOS','MAMIFERO','REPTIL',
    'AVE','AVES','PEIXE','ANFIBIO','FELINO','CANINO','ROEDOR','PRIMATA',
    'MIAU','AUAU','MU','ME','COCORICO','PIU','PIU','CROAC','SSS'
];

// ========== PLANETAS E CÉU ==========
const WORDS_SKY = [
    // planetas / sistema solar
    'SOL','MERCURIO','VENUS','TERRA','MARTE','JUPITER','SATURNO','URANO','NETUNO','PLUTAO',
    'LUA','LUA','CHEIA','NOVA','CRESCENTE','MINGUANTE','ECLIPSE','FASE','FASES',
    'ASTEROIDE','COMETA','METEORO','METEORITO','PLANETA','PLANETAS','SATELITE','ASTRO','ASTROS',
    'ORBITA','GALAXIA','UNIVERSO','COSMOS','VIA','LACTEA','ESPACO','SISTEMA','SOLAR',
    // céu / atmosfera
    'CEU','CEUS','NUVEM','NUVENS','CHUVA','TEMPESTADE','TROVAO','RAIO','RELAMPAGO',
    'VENTO','BRISA','FURACAO','TORNADO','CICLONE','NEVE','GELO','GRANIZO','ORVALHO',
    'NEBLINA','NEVOA','NEVOEIRO','ARCO','IRIS','ARCOIRIS','AURORA','BOREAL','AUSTRAL',
    'ESTRELA','ESTRELAS','CONSTELACAO','ORION','CRUX','ESCORPIAO','LEAO','TOURO','ARIES',
    'PEIXES','CANCER','VIRGEM','LIBRA','SAGITARIO','CAPRICORNIO','AQUARIO','GEMEOS',
    'SOL','NASCENT','POENTE','AMANHECER','ENTARDECER','ANOITECER','MADRUGADA','DIA','NOITE',
    'MANHA','TARDE','CREPUSCULO','HORIZONTE','ZENITE','POENTE','NASCENTE',
    'SOL','CLARO','NUBLADO','ENCUBERTO','ENCOBERTO','ENSOLARADO','CHUVOSO','VENTOSO',
    'CALOR','FRIO','GEADA','CERRADO','SERENO','LUZ','CLARAO','BRILHO','FOGO','FOGOS',
    'FOGUETE','ASTRONAUTA','ASTRONOMO','OBSERVATORIO','TELESCOPIO','BINOCULO','LUNETA',
    'ALIEN','ET','OVNI','DISCO','VOADOR','NAVE','FOGUETE','SATELITE','ESTACAO',
    'CELESTE','SIDERAL','LUNAR','SOLAR','ESTELAR','COSMICO','COSMICA','ORBITAL',
    'ATMOSFERA','OXIGENIO','OZONIO','CAMADA','OZONIO','GRAVIDADE','VACUO','ESPACO',
    'NORTE','SUL','LESTE','OESTE','ESTE','POENTE','NASCENTE','BUSSOLA','ROSA','VENTOS'
];

// ========== NATUREZA ==========
const WORDS_NATURE = [
    'TERRA','SOLO','CHAO','BARRO','AREIA','PEDRA','ROCHA','SEIXO','CASCALHO',
    'MONTANHA','MONTE','MORRO','SERRA','VALE','PLANICIE','PLANALTO','CAMPO',
    'PRADO','PASTO','CERRADO','CAATINGA','MATA','FLORESTA','BOSQUE','SELVA',
    'CAPOEIRA','PANTANAL','DESERTO','OASIS','PRAIA','COSTA','LITORAL','BAIA',
    'ILHA','CAVERNA','GRUTA','BURACO','CRATERA','VULCAO','LAVA','MAGMA',
    'AGUA','MAR','OCEANO','RIO','RIOS','RIACHO','CORREGO','CACHOEIRA','LAGO',
    'LAGOA','REPRESA','ACUDE','POCO','FONTE','NASCENTE','ONDA','ONDAS','MARE',
    'CORRENTE','ESPIMA','GELO','NEVE','GEADA','ORVALHO','CHUVA','TEMPESTADE',
    'TROVAO','RAIO','PLANTA','PLANTAS','ARVORE','ARVORES','TRONCO','GALHO',
    'GALHOS','FOLHA','FOLHAS','FLOR','FLORES','PETALA','SEMENTE','RAIZ','RAIZES',
    'FRUTO','FRUTA','FRUTAS','CASCA','POLPA','CAROCO','ESPINHO','GRAMA','RELVA',
    'MATO','ERVA','ERVAS','MUSGO','FUNGO','COGUMELO','CIPO','SAMAMBAIA','CACTO',
    'PALMEIRA','BAMBU','JUNCO','PINHEIRO','CARVALHO','IPE','EUCALIPTO','ROSA',
    'CRAVO','MARGARIDA','GIRASSOL','ORQUIDEA','LIRIO','VIOLETA','JASMIM',
    'ALECRIM','MANJERICAO','HORTELA','SALSA','CEBOLINHA','COENTRO','ALFACE',
    'COUVE','RUCULA','MILHO','TRIGO','SOJA','CANA','ALGODAO','CACAU',
    'BANANEIRA','COQUEIRO','FOGO','CHAMA','FUMACA','CINZA','BRASA','FOGUEIRA',
    'AR','BRISA','VENTO','VENTANIA','FURACAO','TORNADO','NEBLINA','NEVOA',
    'NEVOEIRO','SOL','LUA','ESTRELA','LUZ','SOMBRA','CALOR','FRIO','UMIDADE',
    'SECA','ENCHENTE','NATUREZA','AMBIENTE','BIOMA','HABITAT','FAUNA','FLORA',
    'PAU','PAUS','MADEIRA','LENHA','TOCO','CEPO','VARA','BASTAO','FOLHAGEM',
    'COPA','RAMO','BROTO','MUDA','VIVEIRO','JARDIM','HORTA','POMAR','PARQUE',
    'RESERVA','TRILHA','TRILHAS','PICADA','CAMINHO','SERRANIA','RIBEIRAO'
];

// ========== VOCABULÁRIO GERAL (já existente + extras) ==========
const WORDS_GENERAL = [
    'SOL','LUA','MAR','RIO','CEU','DIA','MEL','SAL','MAL','PAZ','LUZ','LAR',
    'COR','SOM','TOM','VOZ','REI','ASA','OLA','PAO','MAO','BOI','CAO','UVA',
    'OVO','CHA','SIM','NAO','BOM','MAU','BEM','SEM','COM','POR','SOB','ATE',
    'AMA','AMO','ANO','MES','RUA','BAR','FLOR','DOR','OLE','ORE','TOM','DAR',
    'CASA','MESA','CAMA','COPO','PANO','REDE','SALA','BOLA','PIPA','MEIA',
    'SAIA','ANEL','VASO','LIXO','DOCE','CAFE','SUCO','SOPA','BOLO','GATO',
    'GATA','PATO','RATO','SAPO','LOBO','URSO','VACA','LEAO','MIAU','AMOR',
    'ODIO','MEDO','FOFO','FOFA','BELO','BELA','ALTO','ALTA','NOVO','NOVA',
    'RICO','RICA','ROSA','VIDA','NOME','JOGO','FOTO','RISO','RIOS','DADO',
    'FACA','NADA','TUDO','AQUI','ONDE','QUEM','QUAL','CADA','VOCE','PAIS',
    'LOJA','SINO','TREM','MOTO','BIKE','HORA','HOJE','BEBE','SOFA','FOGO',
    'AGUA','COLA','RODA','FILA','PENA','RIMA','FITA','LADO','MODO','TIPO',
    'CASO','PESO','NOTA','TAPA','CAPA','MAPA','BALA','MALA','BASE','FASE',
    'DOSE','FADA','LAMA','NATA','BODE','BICO','MICO','PICO','SOLO','POLO',
    'GOLA','ROLA','SOLA','SUMO','RUMO','FUMO','MOLA','TROIA','NOEL','MIA',
    'TOMA','TOMO','OREI','ORAR','TOMAR','TOMEI','DATA','NATO','CAMILA',
    'LISTA','TEXTO','HUMOR','MOTOR','VALOR','JUIZ','CRUZ','RAIZ','POSE',
    'GATOS','GATAS','PATOS','RATOS','CASAS','MESAS','JOGOS','FOTOS','LOJAS',
    'IDEIA','BARCO','BANCO','CARRO','TEMPO','MUNDO','FESTA','FILME','SONHO',
    'LINDO','LINDA','FORTE','LEVE','BAIXO','VELHO','CERTO','LEGAL','OTIMO',
    'FACIL','LENTO','CHEIO','VAZIO','SORTE','FORCA','SAUDE','BEIJO','PORTA',
    'LIVRO','CARTA','PAPEL','CAIXA','BOLSA','PRATO','CHAVE','LEITE','ARROZ',
    'CARNE','FRUTA','PEIXE','NOITE','TARDE','MANHA','CHUVA','NUVEM','VENTO',
    'TERRA','PEDRA','FOLHA','CAMPO','PRAIA','AREIA','CALOR','LAGO','ILHA',
    'MONTE','VALE','CLIMA','GENTE','FELIZ','TRISTE','BONITO','POBRE','SUAVE',
    'RUIM','PRECO','PONTE','AVIAO','HORAS','ONTEM','NUNCA','BAIRRO','PRACA',
    'FEIRA','PERTO','LONGE','CIMA','FORA','ANTES','PRONTO','LIVRE','JUNTO',
    'LETRA','CANETA','LAPIS','QUADRO','MUSICA','ESCOLA','CIDADE','JANELA',
    'RADIO','TOALHA','PENTE','TENIS','MASSA','PIZZA','QUEIJO','MOLHO','LIMAO',
    'MACA','PERA','ALHO','MILHO','SOMBRA','NEVE','RAIO','MATO','ONDA','FRIO',
    'SEMANA','AMANHA','SEMPRE','IGREJA','DENTRO','DEPOIS','ABRACO','CARROS',
    'SONHOS','AMIGOS','FILHOS','FLORES','FOLHAS','NUVENS','ONDAS','BANANA',
    'TOMATE','CEBOLA','BATATA','SALADA','FEIJAO','ALMOCO','JANTAR','LANCHE',
    'COMIDA','BEBIDA','PUDIM','PESSOA','PASSARO','CAVALO','COELHO','MACACO',
    'ABELHA','BONITA','QUENTE','GRANDE','ERRADO','RAPIDO','CORAGEM','ALEGRIA',
    'CARINHO','MERCADO','PADARIA','TRABALHO','DINHEIRO','ONIBUS','CACHORRO',
    'GALINHA','LARANJA','MORANGO','FARINHA','AZEITE','BISCOITO','CHOCOLATE',
    'VESTIDO','CASACO','CHINELO','MOCHILA','CELULAR','FOGAO','ESCOVA',
    'SOZINHO','OCUPADO','HISTORIA','PEQUENO','DIFICIL','FORMIGA','GIRAFA',
    'GATINHO','PINTINHO','CAMISA','CALCA','SHORT','BONE','ACUCAR','SORVETE',
    'PALAVRA','NUMERO','PAGINA','PORTAO','ANIMAL','PLANTA','FRUTO','SEMENTE'
];

// ========== ADJETIVOS COMUNS (base masculina; o build gera feminino/plural) ==========
// Cada item: [masc, fem opcional se irregular, substantivo relacionado...]
const ADJECTIVE_BASES = [
    // caráter / moral
    'HONESTO','DESONESTO','FIEL','INFIEL','LEAL','TRAIDOR','MENTIROSO','SINCERO','FALSO',
    'VERDADEIRO','JUSTO','INJUSTO','BOM','MAU','OTIMO','PESSIMO','EXCELENTE','HORRIVEL',
    'LEGAL','ILEGAL','MORAL','IMORAL','ETICO','CORRUPTO','PURO','IMPURO','SANTO','PECADOR',
    'INTEGRO','FRANCO','DIRETO','RETO','NOBRE','DIGNO','VIL','CRUEL','BONDOSO','MALVADO',
    'HONRADO','DESONRADO','VIRTUOSO','VICIOSO','CORRETO','INCORRETO','CERTO','ERRADO',
    // aparência
    'BONITO','LINDO','BELO','FEIO','FOFO','CHARMOSO','ELEGANTE','GRACIOSO','ATRATIVO',
    'GORDO','MAGRO','ALTO','BAIXO','FORTE','FRACO','ATLETICO','ESBELTO','ROBUSTO','DELGADO',
    'GRANDE','PEQUENO','ENORME','GIGANTE','MINUSCULO','CURTO','LONGO','LARGO','ESTREITO',
    'GROSSO','FINO','PESADO','LEVE','CHEIO','VAZIO','VOLUMOSO','FLACIDO','FIRME','MAGRO',
    'GOSTOSO','LINDO','FORMOSO','HORRENDO','RIDICULO','LINDO','FOFO','FOFINHO','LINDAO',
    // cor / tom
    'CLARO','ESCURO','BRANCO','PRETO','MORENO','LOIRO','RUIVO','PALIDO','BRONZEADO','QUEIMADO',
    'COLORIDO','OPACO','BRILHANTE','FOSCO','TRANSPARENTE','METALICO','DOURADO','PRATEADO',
    'VERMELHO','AMARELO','AZULADO','ESVERDEADO','ACINZENTADO','ROXO','ROSADO','MARROM',
    // personalidade
    'ALEGRE','TRISTE','CALMO','NERVOSO','BRAVO','DOCE','AMAVEL','GENTIL','EDUCADO','GROSSEIRO',
    'TIMIDO','EXTROVERTIDO','INTROVERTIDO','INTELIGENTE','ESPERTO','BURRO','SABIO','GENIAL',
    'CRIATIVO','CURIOSO','ATENTO','DISTRAIDO','PACIENTE','IMPACIENTE','GENEROSO','EGOISTA',
    'CIUMENTO','CORAJOSO','COVARDE','MEDROSO','OUSADO','TRANQUILO','ANSIOSO','ESTRESSADO',
    'CANSADO','ANIMADO','MOTIVADO','PREGUICOSO','TRABALHADOR','DEDICADO','ORGANIZADO',
    'DESORGANIZADO','LIMPO','SUJO','SAUDAVEL','DOENTE','ATIVO','SEDENTARIO','JOVEM','VELHO',
    'MADURO','IMATURO','ADULTO','IDOSO','RICO','POBRE','MODESTO','HUMILDE','ORGULHOSO',
    'FELIZ','INFELIZ','SORTUDO','AZARADO','OTIMISTA','PESSIMISTA','ROMANTICO','CARINHOSO',
    'FRIO','QUENTE','DIVERTIDO','CHATO','ENGRACADO','SERIO','BRINCALHAO','BAGUNCEIRO',
    'RESPONSAVEL','IRRESPONSAVEL','PONTUAL','ATRASADO','RAPIDO','LENTO','HABILIDOSO',
    'DESAJEITADO','AGIL','CEGO','SURDO','MUDO','CANHOTO','DESTRO','BILINGUE','ANALFABETO',
    'SARDENTO','CACHEADO','LISO','CRESPO','ONDULADO','CALVO','GRISALHO','BARBUDO',
    'AMIGAVEL','HOSTIL','SOCIAVEL','ANTISSOCIAL','SIMPATICO','ANTIPATICO','AFETUOSO',
    'SENSIVEL','INSENSIVEL','EMPATICO','CIUMENTO','INVEJOSO','ORGULHOSO','VANIDOSO',
    'MODESTO','SIMPLES','COMPLICADO','FACIL','DIFICIL','OBVIO','CONFUSO','CLARO',
    // estados / qualidade
    'NOVO','VELHO','USADO','ANTIGO','MODERNO','ATUAL','RECENTE','FUTURO','PROXIMO','ANTERIOR',
    'ULTIMO','PRIMEIRO','SEGUNDO','TERCEIRO','UNICO','DUPLO','TRIPLO','INTEIRO','PARCIAL',
    'TOTAL','GERAL','PARTICULAR','PUBLICO','PRIVADO','PESSOAL','COLETIVO','INTERNO','EXTERNO',
    'ABERTO','FECHADO','LIGADO','DESLIGADO','PRONTO','PREPARADO','ACABADO','COMPLETO',
    'INCOMPLETO','CERTO','ERRADO','POSSIVEL','IMPOSSIVEL','NECESSARIO','IMPORTANTE','URGENTE',
    'SIMPLES','COMPLEXO','FACIL','DIFICIL','NORMAL','ESTRANHO','COMUM','RARO','ESPECIAL',
    'USUAL','HABITUAL','DIARIO','SEMANAL','MENSAL','ANUAL','ETERNO','TEMPORARIO','FIXO',
    'MOVEL','PARADO','SEGURO','PERIGOSO','TRANQUILO','PREOCUPADO','ALIVIADO','CONTENTE',
    'SATISFEITO','INSATISFEITO','CONFIANTE','INSEGURO','PODEROSO','FRACO','VITORIOSO',
    'DERROTADO','SUCEDIDO','FRACASSADO','OCUPADO','LIVRE','SOZINHO','ACOMPANHADO',
    'ISOLADO','UNIDO','SEPARADO','JUNTO','PERTO','LONGE','DENTRO','FORA',
    'QUENTE','FRIO','MORNO','GELADO','UMIDO','SECO','MOLHADO','SUJO','LIMPO',
    'DOCE','SALGADO','AZEDO','AMARGO','SUAVE','FORTE','DURO','MOLE','MACIO','ASPERO',
    'LISO','RUGOSO','AFILADO','PONTUDO','REDONDO','QUADRADO','OVAL','RETO','CURVO',
    'DIREITO','ESQUERDO','SUPERIOR','INFERIOR','ANTERIOR','POSTERIOR','CENTRAL','LATERAL',
    'NATURAL','ARTIFICIAL','REAL','IRREAL','VERDADEIRO','FALSO','ORIGINAL','COPIADO',
    'PROPRIO','ALHEIO','MESMO','OUTRO','TAL','QUALQUER','CADA','TODO','NENHUM',
    'MUITO','POUCO','BASTANTE','DEMAIS','MEIO','QUASE',
    'AMADO','ODIADO','QUERIDO','ESTIMADO','RESPEITADO','ADMIRADO','INVEJADO','TEMIDO',
    'CONHECIDO','DESCONHECIDO','FAMOSO','ANONIMO','POPULAR','IMPOULAR','COMUM','RARO',
    'NASCIDO','MORTO','VIVO','SAUDAVEL','DOENTE','CURADO','FERIDO','MACHUCADO','SAO',
    'CASADO','SOLTEIRO','VIUVO','DIVORCIADO','NOIVO','NAMORADO','ADOTADO','ADOTIVO',
    'NATURAL','ADOTIVO','MATERNO','PATERNO','FILIAL','FRATERNO','AMIGAVEL','HOSTIL',
    'PACIFICO','AGRESSIVO','VIOLENTO','CALMO','SERENO','TURBULENTO','CAOTICO','ORDENADO',
    'LIMPO','ORGANIZADO','BAGUNCADO','ARRUMADO','DESARRUMADO','FEDIDO',
    'CHEIROSO','PERFUMADO','PODRE','FRESCO','ESTRAGADO','CRU','COZIDO','ASSADO',
    'FRITO','MADURO','VERDE','SECO','MOLHADO','CONGELADO','DERRETIDO',
    // valor / preço / utilidade
    'CARO','BARATO','GRATIS','UTIL','INUTIL','CAPAZ','INCAPAZ','APTO','INEPTO',
    'VALIDO','INVALIDO','OFICIAL','EXTRA','BASICO','AVANCADO','IDEAL','PERFEITO',
    'IMPERFEITO','PRINCIPAL','SECUNDARIO','FINAL','INICIAL','MEDIO','MAXIMO','MINIMO',
    'LOCAL','GLOBAL','SOCIAL','CIVIL','HUMANO','ANIMAL','VEGETAL','MINERAL',
    'VISIVEL','INVISIVEL','AUDIVEL','SENSIVEL','TERRIVEL','MARAVILHOSO','FANTASTICO',
    'INCRIVEL','ESPETACULAR','OTIMO','PESSIMO','RUIM','LEGAL','BACANA','MANEIRO',
    'LOUCO','MALUCO','DOIDO','SANO','SAO','SERIO','GRAVE','LEVE','FUNDO','RASO',
    'NU','DESCALCO','CALCADO','ARMADO','DESARMADO','PROTEGIDO','EXPOSTO',
    'ESCONDIDO','REVELADO','ABERTO','FECHADO'
];

// Formas M/F/plural explícitas dos adjetivos mais comuns (garante cobertura mesmo se expand falhar)
const ADJECTIVE_FORMS = [
    // honesto e família
    'HONESTO','HONESTA','HONESTOS','HONESTAS',
    'DESONESTO','DESONESTA','DESONESTOS','DESONESTAS',
    'SINCERO','SINCERA','SINCEROS','SINCERAS',
    'MENTIROSO','MENTIROSA','MENTIROSOS','MENTIROSAS',
    'FIEL','FIEIS','INFIEL','INFIEIS','LEAL','LEAIS',
    'TRAIDOR','TRAIDORA','TRAIDORES','TRAIDORAS',
    'JUSTO','JUSTA','JUSTOS','JUSTAS','INJUSTO','INJUSTA','INJUSTOS','INJUSTAS',
    'INTEGRO','INTEGRA','INTEGROS','INTEGRAS',
    'FRANCO','FRANCA','FRANCOS','FRANCAS',
    'VERDADEIRO','VERDADEIRA','VERDADEIROS','VERDADEIRAS',
    'FALSO','FALSA','FALSOS','FALSAS','CORRUPTO','CORRUPTA','CORRUPTOS','CORRUPTAS',
    'HONRADO','HONRADA','HONRADOS','HONRADAS','PURO','PURA','PUROS','PURAS',
    'BOM','BOA','BONS','BOAS','MAU','MAUS','OTIMO','OTIMA','OTIMOS','OTIMAS',
    'PESSIMO','PESSIMA','PESSIMOS','PESSIMAS','RUIM','RUINS','LEGAL','LEGAIS',
    // aparência
    'BONITO','BONITA','BONITOS','BONITAS','LINDO','LINDA','LINDOS','LINDAS',
    'BELO','BELA','BELOS','BELAS','FEIO','FEIA','FEIOS','FEIAS',
    'FOFO','FOFA','FOFOS','FOFAS','CHARMOSO','CHARMOSA','CHARMOSOS','CHARMOSAS',
    'GORDO','GORDA','GORDOS','GORDAS','MAGRO','MAGRA','MAGROS','MAGRAS',
    'ALTO','ALTA','ALTOS','ALTAS','BAIXO','BAIXA','BAIXOS','BAIXAS',
    'FORTE','FORTES','FRACO','FRACA','FRACOS','FRACAS',
    'GRANDE','GRANDES','PEQUENO','PEQUENA','PEQUENOS','PEQUENAS',
    'CURTO','CURTA','CURTOS','CURTAS','LONGO','LONGA','LONGOS','LONGAS',
    'GROSSO','GROSSA','GROSSOS','GROSSAS','FINO','FINA','FINOS','FINAS',
    'PESADO','PESADA','PESADOS','PESADAS','LEVE','LEVES','CHEIO','CHEIA','CHEIOS','CHEIAS',
    'VAZIO','VAZIA','VAZIOS','VAZIAS','NOVO','NOVA','NOVOS','NOVAS',
    'VELHO','VELHA','VELHOS','VELHAS','JOVEM','JOVENS','ADULTO','ADULTA','ADULTOS','ADULTAS',
    // cores / traços
    'CLARO','CLARA','CLAROS','CLARAS','ESCURO','ESCURA','ESCUROS','ESCURAS',
    'BRANCO','BRANCA','BRANCOS','BRANCAS','PRETO','PRETA','PRETOS','PRETAS',
    'MORENO','MORENA','MORENOS','MORENAS','LOIRO','LOIRA','LOIROS','LOIRAS',
    'RUIVO','RUIVA','RUIVOS','RUIVAS','SARDENTO','SARDENTA','SARDENTOS','SARDENTAS',
    'CACHEADO','CACHEADA','CACHEADOS','CACHEADAS','LISO','LISA','LISOS','LISAS',
    'CRESPO','CRESPA','CRESPOS','CRESPAS','ONDULADO','ONDULADA','ONDULADOS','ONDULADAS',
    'CALVO','CALVA','CALVOS','CALVAS','GRISALHO','GRISALHA','GRISALHOS','GRISALHAS',
    // personalidade
    'ALEGRE','ALEGRES','TRISTE','TRISTES','CALMO','CALMA','CALMOS','CALMAS',
    'NERVOSO','NERVOSA','NERVOSOS','NERVOSAS','BRAVO','BRAVA','BRAVOS','BRAVAS',
    'DOCE','DOCES','AMAVEL','AMAVEIS','GENTIL','GENTEIS','EDUCADO','EDUCADA','EDUCADOS','EDUCADAS',
    'TIMIDO','TIMIDA','TIMIDOS','TIMIDAS','ESPERTO','ESPERTA','ESPERTOS','ESPERTAS',
    'BURRO','BURRA','BURROS','BURRAS','SABIO','SABIA','SABIOS','SABIAS',
    'CRIATIVO','CRIATIVA','CRIATIVOS','CRIATIVAS','CURIOSO','CURIOSA','CURIOSOS','CURIOSAS',
    'ATENTO','ATENTA','ATENTOS','ATENTAS','PACIENTE','PACIENTES',
    'GENEROSO','GENEROSA','GENEROSOS','GENEROSAS','EGOISTA','EGOISTAS',
    'CIUMENTO','CIUMENTA','CIUMENTOS','CIUMENTAS','CORAJOSO','CORAJOSA','CORAJOSOS','CORAJOSAS',
    'MEDROSO','MEDROSA','MEDROSOS','MEDROSAS','OUSADO','OUSADA','OUSADOS','OUSADAS',
    'TRANQUILO','TRANQUILA','TRANQUILOS','TRANQUILAS','ANSIOSO','ANSIOSA','ANSIOSOS','ANSIOSAS',
    'CANSADO','CANSADA','CANSADOS','CANSADAS','ANIMADO','ANIMADA','ANIMADOS','ANIMADAS',
    'MOTIVADO','MOTIVADA','MOTIVADOS','MOTIVADAS','PREGUICOSO','PREGUICOSA','PREGUICOSOS','PREGUICOSAS',
    'DEDICADO','DEDICADA','DEDICADOS','DEDICADAS','ORGANIZADO','ORGANIZADA','ORGANIZADOS','ORGANIZADAS',
    'LIMPO','LIMPA','LIMPOS','LIMPAS','SUJO','SUJA','SUJOS','SUJAS',
    'SAUDAVEL','SAUDAVEIS','DOENTE','DOENTES','ATIVO','ATIVA','ATIVOS','ATIVAS',
    'RICO','RICA','RICOS','RICAS','POBRE','POBRES','MODESTO','MODESTA','MODESTOS','MODESTAS',
    'HUMILDE','HUMILDES','ORGULHOSO','ORGULHOSA','ORGULHOSOS','ORGULHOSAS',
    'FELIZ','FELIZES','INFELIZ','INFELIZES','SORTUDO','SORTUDA','SORTUDOS','SORTUDAS',
    'AZARADO','AZARADA','AZARADOS','AZARADAS','OTIMISTA','OTIMISTAS','PESSIMISTA','PESSIMISTAS',
    'ROMANTICO','ROMANTICA','ROMANTICOS','ROMANTICAS','CARINHOSO','CARINHOSA','CARINHOSOS','CARINHOSAS',
    'FRIO','FRIA','FRIOS','FRIAS','QUENTE','QUENTES','DIVERTIDO','DIVERTIDA','DIVERTIDOS','DIVERTIDAS',
    'CHATO','CHATA','CHATOS','CHATAS','ENGRACADO','ENGRACADA','ENGRACADOS','ENGRACADAS',
    'SERIO','SERIA','SERIOS','SERIAS','RAPIDO','RAPIDA','RAPIDOS','RAPIDAS',
    'LENTO','LENTA','LENTOS','LENTAS','CEGO','CEGA','CEGOS','CEGAS',
    'SURDO','SURDA','SURDOS','SURDAS','MUDO','MUDA','MUDOS','MUDAS',
    'CANHOTO','CANHOTA','CANHOTOS','CANHOTAS','DESTRO','DESTRA','DESTROS','DESTRAS',
    'SIMPATICO','SIMPATICA','SIMPATICOS','SIMPATICAS','ANTIPATICO','ANTIPATICA',
    // estados
    'ABERTO','ABERTA','ABERTOS','ABERTAS','FECHADO','FECHADA','FECHADOS','FECHADAS',
    'PRONTO','PRONTA','PRONTOS','PRONTAS','CERTO','CERTA','CERTOS','CERTAS',
    'ERRADO','ERRADA','ERRADOS','ERRADAS','FACIL','FACEIS','DIFICIL','DIFICEIS',
    'SIMPLES','COMPLEXO','COMPLEXA','COMPLEXOS','COMPLEXAS',
    'NORMAL','NORMAIS','ESTRANHO','ESTRANHA','ESTRANHOS','ESTRANHAS',
    'COMUM','COMUNS','RARO','RARA','RAROS','RARAS','ESPECIAL','ESPECIAIS',
    'SEGURO','SEGURA','SEGUROS','SEGURAS','PERIGOSO','PERIGOSA','PERIGOSOS','PERIGOSAS',
    'LIVRE','LIVRES','OCUPADO','OCUPADA','OCUPADOS','OCUPADAS',
    'SOZINHO','SOZINHA','SOZINHOS','SOZINHAS','UNIDO','UNIDA','UNIDOS','UNIDAS',
    'SEPARADO','SEPARADA','SEPARADOS','SEPARADAS','JUNTO','JUNTA','JUNTOS','JUNTAS',
    'PERTO','PERTOS','LONGE','LONGES','MORNO','MORNA','MORNOS','MORNAS',
    'GELADO','GELADA','GELADOS','GELADAS','UMIDO','UMIDA','UMIDOS','UMIDAS',
    'SECO','SECA','SECOS','SECAS','MOLHADO','MOLHADA','MOLHADOS','MOLHADAS',
    'SALGADO','SALGADA','SALGADOS','SALGADAS','AZEDO','AZEDA','AZEDOS','AZEDAS',
    'AMARGO','AMARGA','AMARGOS','AMARGAS','SUAVE','SUAVES','DURO','DURA','DUROS','DURAS',
    'MOLE','MOLES','MACIO','MACIA','MACIOS','MACIAS',
    'REDONDO','REDONDA','REDONDOS','REDONDAS','RETO','RETA','RETOS','RETAS',
    'CURVO','CURVA','CURVOS','CURVAS','DIREITO','DIREITA','DIREITOS','DIREITAS',
    'ESQUERDO','ESQUERDA','ESQUERDOS','ESQUERDAS','PROPRIO','PROPRIA','PROPRIOS','PROPRIAS',
    'MESMO','MESMA','MESMOS','MESMAS','OUTRO','OUTRA','OUTROS','OUTRAS',
    'AMADO','AMADA','AMADOS','AMADAS','QUERIDO','QUERIDA','QUERIDOS','QUERIDAS',
    'FAMOSO','FAMOSA','FAMOSOS','FAMOSAS','POPULAR','POPULARES',
    'VIVO','VIVA','VIVOS','VIVAS','MORTO','MORTA','MORTOS','MORTAS',
    'CASADO','CASADA','CASADOS','CASADAS','SOLTEIRO','SOLTEIRA','SOLTEIROS','SOLTEIRAS',
    'VIUVO','VIUVA','VIUVOS','VIUVAS','NOIVO','NOIVA','NOIVOS','NOIVAS',
    'NAMORADO','NAMORADA','NAMORADOS','NAMORADAS','ADOTADO','ADOTADA','ADOTADOS','ADOTADAS',
    'CARO','CARA','CAROS','CARAS','BARATO','BARATA','BARATOS','BARATAS',
    'UTIL','UTEIS','INUTIL','INUTEIS','CAPAZ','CAPAZES','PERFEITO','PERFEITA','PERFEITOS','PERFEITAS',
    'BASICO','BASICA','BASICOS','BASICAS','FINAL','FINAIS','MEDIO','MEDIA','MEDIOS','MEDIAS',
    'LOUCO','LOUCA','LOUCOS','LOUCAS','MALUCO','MALUCA','MALUCOS','MALUCAS',
    'DOIDO','DOIDA','DOIDOS','DOIDAS','NU','NUA','NUS','NUAS',
    'BRINCALHAO','BRINCALHONA','BRINCALHOES','BRINCALHONAS',
    'TRABALHADOR','TRABALHADORA','TRABALHADORES','TRABALHADORAS',
    'RESPONSAVEL','RESPONSAVEIS','INTELIGENTE','INTELIGENTES',
    'IMPORTANTE','IMPORTANTES','NECESSARIO','NECESSARIA','NECESSARIOS','NECESSARIAS',
    'POSSIVEL','POSSIVEIS','IMPOSSIVEL','IMPOSSIVEIS','DIVERTIDO','DIVERTIDA',
    'ROMANTICO','ROMANTICA','ORGULHOSO','ORGULHOSA','CARINHOSO','CARINHOSA',
    'PREGUICOSO','PREGUICOSA','ESTRESSADO','ESTRESSADA','DISTRAIDO','DISTRAIDA',
    'GROSSEIRO','GROSSEIRA','HABILIDOSO','HABILIDOSA','DESAJEITADO','DESAJEITADA',
    'MARAVILHOSO','MARAVILHOSA','FANTASTICO','FANTASTICA','INCRIVEL','INCRIVEIS',
    'TERRIVEL','TERRIVEIS','HORRIVEL','HORRIVEIS','EXCELENTE','EXCELENTES'
];

// Substantivos relacionados a adjetivos (até 10 letras no build)
const ADJECTIVE_RELATED = [
    'HONRA','HONRAS','ETICA','MORAL','VIRTUDE','VICIO','VICIOS','MENTIRA','VERDADE',
    'JUSTICA','BONDADE','MALDADE','LEALDADE','TRAICAO','FIDELIDADE','FRAUDE','GOLPE',
    'BELEZA','FEIURA','CHARME','FORCA','FRAQUEZA','ALTURA','PESO','TAMANHO',
    'SARDA','SARDAS','PINTA','PINTAS','MANCHA','MANCHAS','CICATRIZ','RUGAS',
    'ALEGRIA','TRISTEZA','CALMA','RAIVA','MEDO','CORAGEM','COVARDIA','CIUME',
    'INVEJA','ORGULHO','HUMILDADE','TIMIDEZ','ATENCAO','DISTRACAO','GENIO',
    'BURRICE','SABEDORIA','IDEIA','IDEIAS','SONHO','SONHOS','FELICIDADE','SORTE','AZAR',
    'OTIMISMO','ROMANCE','CARINHO','FRIEZA','DIVERSAO','TEDIO','AMOR','ODIO','PAIXAO',
    'AFETO','ESTIMA','RESPEITO','ADMIRACAO','TEMOR','FAMA','AMIZADE','PAZ','GUERRA',
    'SAUDE','DOENCA','VIDA','MORTE','CURA','IDADE','RIQUEZA','POBREZA','PODER',
    'SUCESSO','FRACASSO','VITORIA','DERROTA','LIBERDADE','SOLIDAO','UNIAO',
    'CASAMENTO','NOIVADO','NAMORO','ADOCAO','DIVORCIO','VIUVEZ','TRABALHO','FOLGA',
    'DESCANSO','CANSACO','LIMPEZA','SUJEIRA','BAGUNCA','ORDEM','CAOS','SEGURANCA',
    'PERIGO','CONFIANCA','CHEIRO','PERFUME','FEDOR','FRESCOR','CALOR','FRIO','FOGO',
    'HONESTO','HONESTA','HONESTOS','HONESTAS','DESONESTO','DESONESTA',
    'SINCERO','SINCERA','MENTIROSO','MENTIROSA','LEAL','FIEL','JUSTO','JUSTA'
];

// Substantivos comuns com pares M/F/plural
const NOUN_COMMON = [
    'HOMEM','HOMENS','MULHER','MULHERES','MENINO','MENINA','MENINOS','MENINAS',
    'RAPAZ','RAPAZES','MOCA','MOCAS','SENHOR','SENHORA','DONA','DONO','DONOS',
    'PESSOA','PESSOAS','GENTE','POVO','CRIANCA','CRIANCAS','BEBE','BEBES',
    'AMIGO','AMIGA','AMIGOS','AMIGAS','VIZINHO','VIZINHA','COLEGA','COLEGAS',
    'CHEFE','CHEFES','PATRAO','PATROA','SOCIO','SOCIA','CLIENTE','CLIENTES',
    'CASA','CASAS','LAR','LARES','SALA','SALAS','QUARTO','QUARTOS','COZINHA',
    'BANHEIRO','PORTA','PORTAS','JANELA','JANELAS','TELHADO','PAREDE','CHAO','TETO',
    'RUA','RUAS','PRACA','PRACAS','BAIRRO','BAIRROS','CIDADE','CIDADES','PAIS',
    'ESCOLA','ESCOLAS','IGREJA','IGREJAS','LOJA','LOJAS','MERCADO','FEIRA','HOSPITAL',
    'PARQUE','PARQUES','PRAIA','PRAIAS','CAMPO','CAMPOS','FLORESTA','MATO','JARDIM',
    'MESA','MESAS','CADEIRA','CAMA','CAMAS','SOFA','SOFAS','COPO','COPOS',
    'PRATO','PRATOS','COLHER','FACA','GARFO','PANELA','FOGAO','LIVRO','LIVROS',
    'CANETA','LAPIS','PAPEL','PAPEIS','CARTA','CARTAS','BOLSA','BOLSAS',
    'CHAVE','CHAVES','RELOGIO','OCULOS','SAPATO','SAPATOS','CAMISA','CAMISAS','CALCA',
    'VESTIDO','SAIA','SAIAS','BONE','BONES','CHAPEU','CHAPEUS','MEIA','MEIAS',
    'CARRO','CARROS','MOTO','MOTOS','ONIBUS','TREM','TRENS','AVIAO','AVIOES',
    'BARCO','BARCOS','BOLA','BOLAS','BONECA','BONECO','BRINQUEDO','JOGO','JOGOS',
    'COMIDA','BEBIDA','AGUA','LEITE','SUCO','SUCOS','CAFE','CHA','CERVEJA','VINHO',
    'PAO','PAES','ARROZ','FEIJAO','CARNE','PEIXE','OVO','OVOS','FRUTA','FRUTAS',
    'MACA','PERA','UVA','UVAS','BANANA','LARANJA','LIMAO','TOMATE','BATATA','CEBOLA',
    'ALFACE','SALADA','SOPA','SOPAS','BOLO','BOLOS','DOCE','DOCES','SORVETE','PIZZA',
    'DIA','DIAS','NOITE','NOITES','MANHA','TARDE','HORA','HORAS','MINUTO','SEGUNDO',
    'SEMANA','MES','MESES','ANO','ANOS','HOJE','ONTEM','AMANHA','TEMPO','CLIMA',
    'SOL','LUA','ESTRELA','ESTRELAS','CEU','NUVEM','NUVENS','CHUVA','VENTO','RAIO',
    'MAR','MARES','RIO','RIOS','LAGO','LAGOS','TERRA','PEDRA','PEDRAS','AREIA',
    'FOLHA','FOLHAS','FLOR','FLORES','ARVORE','ARVORES','MATO','FOGO','FUMACA','GELO',
    'AMOR','ODIO','MEDO','RAIVA','DOR','DORES','PRAZER','PAZ','GUERRA','VIDA','MORTE',
    'NOME','NOMES','IDADE','COR','CORES','SOM','SONS','LUZ','LUZES','SOMBRA',
    'IDEIA','IDEIAS','SONHO','SONHOS','PLANO','PLANOS','META','METAS','FATO',
    'CAUSA','EFEITO','MEIO','FIM','FINS','INICIO','COMECO','FINAL','PARTE',
    'LADO','LADOS','MODO','MODOS','TIPO','TIPOS','FORMA','FORMAS','JEITO',
    'VALOR','VALORES','PRECO','PRECOS','PESO','PESOS','MEDIDA','NUMERO','NUMEROS',
    'LETRA','LETRAS','PALAVRA','FRASE','FRASES','TEXTO','TEXTOS','HISTORIA','CONTO',
    'MUSICA','CANCAO','FILME','FILMES','FOTO','FOTOS','IMAGEM','SILENCIO',
    'VERDADE','MENTIRA','REGRA','REGRAS','LEI','LEIS','DIREITO','DEVER',
    'HONRA','ETICA','MORAL','CULPA','VERGONHA','ORGULHO','FE','ESPERANCA','SORTE'
];

const WORDS_COMMON_EXTRA = [
    // lamúria e relacionados
    'LAMURIA','LAMURIAS','LAMURIAR','LAMURIO','LAMURIAS','LAMURIA','LAMURIAM',
    'LAMURIEI','LAMURIOU','LAMURIADO','LAMURIADA','LAMURIANDO','LAMENTO','LAMENTAR',
    'LAMENTO','LAMENTA','LAMENTEI','LAMENOU','LAMENTADO','LAMENTANDO','QUEIXA',
    'QUEIXAR','QUEIXO','QUEIXA','RECLAMA','RECLAMAR','RECLAMO','RECLAMOU','CHORO',
    'CHORAR','SOLUCO','SOLUCAR','GEMIDO','GEMER','GEME','GEMI','GEMEU','SUSPIRO',
    'SUSPIRAR','SUSPIRA','CHORO','PRANTO','LAGRIMA','LAGRIMAS','TRISTEZA','ANGUSTIA',
    'ANSIEDADE','MEDO','PANICO','RAIVA','ODIO','CIUME','INVEJA','ORGULHO',
    'VERGONHA','CULPA','REMORSO','SAUDADE','NOSTALGIA','ESPERANCA','FE',
    // vida cotidiana
    'CASA','LAR','MORADIA','APARTAMENTO','SOBRADO','SITIO','FAZENDA','CHACARA',
    'RUA','AVENIDA','BECO','TRAVESSA','PRACA','CALCADA','PASSEIO','PONTE',
    'ESCOLA','FACULDADE','UNIVERSIDADE','CRECHE','CURSO','AULA','PROVA','NOTA',
    'TRABALHO','EMPREGO','SERVICO','OFICIO','CARREIRA','SALARIO','FERIAS','FOLGA',
    'DINHEIRO','TROCO','PAGAMENTO','CONTA','DIVIDA','EMPRESTIMO','JUROS','LUCRO',
    'PREJUIZO','DESPESA','RECEITA','ORCAMENTO','ECONOMIA','POUPANCA','INVESTIMENTO',
    'COMIDA','REFEICAO','CAFE','LANCHE','ALMOCO','JANTAR','CEIA','PETISCO',
    'FOME','SEDE','APETITE','SACIEDADE','GULOSEIMA','SOBREMESA','ENTRADA','PRATO',
    'SAUDE','DOENCA','FEBRE','TOSSE','GRIPE','RESFRIADO','DOR','FERIDA','CURA',
    'REMEDIO','PILULA','XAROPE','VACINA','EXAME','CONSULTA','CIRURGIA','ALTA',
    'HOSPITAL','POSTO','CLINICA','FARMACIA','PRONTO','SOCORRO','AMBULANCIA',
    'AMOR','CARINHO','BEIJO','ABRACO','AFETO','PAIXAO','ROMANCE','CASAMENTO',
    'DIVORCIO','SEPARACAO','NOIVADO','NAMORO','FICADA','PAQUERA','CIUME',
    'AMIZADE','COLEGA','VIZINHO','VIZINHA','CONHECIDO','CONHECIDA','ESTRANHO',
    'VIAGEM','PASSEIO','TURISMO','FERIAS','FOGEIRA','FOGUEIRA','ACAMPAMENTO',
    'PRAIA','PISCINA','PARQUE','CINEMA','TEATRO','SHOW','FESTA','ANIVERSARIO',
    'CASAMENTO','BATIZADO','FUNERAL','FORMATURA','REUNIAO','ENCONTRO','CITA',
    'TEMPO','HORA','MINUTO','SEGUNDO','DIA','SEMANA','MES','ANO','SECULO',
    'PASSADO','PRESENTE','FUTURO','AGORA','ANTES','DEPOIS','CEDO','TARDE',
    'SEMPRE','NUNCA','ASVEZES','JA','AINDA','LOGO','ENTAO','DEPOIS','ANTES',
    'SIM','NAO','TALVEZ','CLARO','OBVIO','CERTO','ERRADO','VERDADE','MENTIRA',
    'BOM','RUIM','OTIMO','PESSIMO','LEGAL','CHATO','FACIL','DIFICIL','POSSIVEL',
    'IMPOSSIVEL','NECESSARIO','IMPORTANTE','URGENTE','SIMPLES','COMPLEXO',
    'GRANDE','PEQUENO','ENORME','GIGANTE','MINIMO','MAXIMO','MEDIO','MEDIA',
    'INICIO','COMECO','MEIO','FIM','FINAL','COMECO','TERMINO','RESULTADO',
    'CAUSA','MOTIVO','RAZAO','OBJETIVO','META','SONHO','PLANO','IDEIA','IDEIA',
    'PROBLEMA','SOLUCAO','DUVIDA','PERGUNTA','RESPOSTA','PERGUNTA','RESPOSTA',
    'NUMERO','LETRA','PALAVRA','FRASE','TEXTO','LIVRO','PAGINA','CAPITULO',
    'HISTORIA','CONTO','NOVELA','ROMANCE','POEMA','MUSICA','CANCAO','LETRA',
    'JOGO','BRINCADEIRA','DIVERSÃO','DIVERSAO','LAZER','HOBBY','ESPORTE','TIME',
    'VITORIA','DERROTA','EMPATE','GOL','PONTO','PLACAR','CAMPEAO','CAMPEA',
    'PERDEDOR','PERDEDORA','VENCEDOR','VENCEDORA','JOGADOR','JOGADORA',
    'NOTICIA','JORNAL','REVISTA','INTERNET','SITE','REDE','SOCIAL','EMAIL',
    'MENSAGEM','LIGACAO','CHAMADA','VIDEO','CHAMADA','FOTO','IMAGEM','SOM',
    'SILENCIO','BARULHO','RUIDO','ECO','ECOAR','ECOOU','RESSONAR','RESSOA',
    'LUZ','ESCURIDAO','SOMBRA','CLARAO','BRILHO','FOGO','FUMAÇA','FUMACA',
    'PORTA','JANELA','CHAVE','FECHADURA','CADEADO','SERRALHEIRO','ALARME',
    'CARRO','MOTO','ONIBUS','TREM','AVIAO','BARCO','BICICLETA','PATINETE',
    'GASOLINA','ALCOOL','DIESEL','BATERIA','PNEU','VOLANTE','FREIO','ACELERADOR',
    'DIRECAO','MAPA','GPS','ROTA','CAMINHO','DESTINO','ORIGEM','CHEGADA','PARTIDA',
    'ENTRADA','SAIDA','ACESSO','BLOQUEIO','PERMISSAO','PROIBICAO','REGRA','LEI',
    'DIREITO','DEVER','OBRIGACAO','LIBERDADE','JUSTICA','INJUSTICA','CRIME','PENA',
    'POLICIA','LADRAO','LADRA','VITIMA','TESTEMUNHA','PROVA','JULGAMENTO','SENTENCA',
    'GOVERNO','ESTADO','PAIS','CIDADE','BAIRRO','POVO','NACAO','BANDEIRA','HINO',
    'ELEICAO','VOTO','URNA','CANDIDATO','CANDIDATA','PARTIDO','POLITICA','LEI',
    'IMPOSTO','TAXA','MULTA','DOCUMENTO','IDENTIDADE','PASSAPORTE','CARTEIRA',
    'HABILITACAO','CERTIDAO','CONTRATO','RECIBO','NOTA','FISCAL','CUPOM',
    'COMPRA','VENDA','TROCA','DOACAO','PRESENTE','BRINDE','OFERTA','PROMOCAO',
    'DESCONTO','PRECO','VALOR','BARATO','CARO','GRATIS','PAGO','PAGA','PAGO',
    'CLIENTE','VENDEDOR','VENDEDORA','LOJA','MERCADO','SHOPPING','FEIRA','BANCA',
    'PRODUTO','MERCADORIA','ESTOQUE','PEDIDO','ENTREGA','FRETE','EMBALAGEM',
    'QUALIDADE','QUANTIDADE','MEDIDA','PESO','ALTURA','LARGURA','COMPRIMENTO',
    'TAMANHO','MODELO','COR','MARCA','TIPO','ESTILO','FORMA','FORMATO','PADRAO',
    'EXEMPLO','MODELO','AMOSTRA','COPIA','ORIGINAL','FALSO','FALSA','VERDADEIRO',
    'VERDADEIRA','REAL','IRREAL','NORMAL','ESTRANHO','ESTRANHA','COMUM','RARO',
    'RARA','ESPECIAL','COMUM','USUAL','HABITUAL','DIARIO','DIARIA','SEMANAL',
    'MENSAL','ANUAL','ETERNO','ETERNA','TEMPORARIO','TEMPORARIA','FIXO','FIXA',
    'MOVEL','PARADO','PARADA','RAPIDO','RAPIDA','LENTO','LENTA','DEVAGAR','DEPRESSA',
    'CEDO','TARDE','PONTUAL','ATRASADO','ATRASADA','ADIANTADO','ADIANTADA',
    'CHEIO','CHEIA','VAZIO','VAZIA','COMPLETO','COMPLETA','INCOMPLETO','INCOMPLETA',
    'ABERTO','ABERTA','FECHADO','FECHADA','LIGADO','LIGADA','DESLIGADO','DESLIGADA',
    'LIGADO','PRONTO','PRONTA','PREPARADO','PREPARADA','ACABADO','ACABADA','PRONTO',
    'NOVO','NOVA','VELHO','VELHA','USADO','USADA','NOVO','ANTIGO','ANTIGA','MODERNO',
    'MODERNA','ATUAL','DESATUALIZADO','DESATUALIZADA','RECENTE','ANTIGO','FUTURO',
    'PROXIMO','PROXIMA','ANTERIOR','SEGUINTE','ULTIMO','ULTIMA','PRIMEIRO','PRIMEIRA',
    'SEGUNDO','SEGUNDA','TERCEIRO','TERCEIRA','UNICO','UNICA','DUPLO','DUPLA','TRIPLO',
    'MEIO','METADE','INTEIRO','INTEIRA','PARCIAL','TOTAL','GERAL','PARTICULAR',
    'PUBLICO','PUBLICA','PRIVADO','PRIVADA','PESSOAL','COLETIVO','COLETIVA',
    'INTERNO','INTERNA','EXTERNO','EXTERNA','DENTRO','FORA','ACIMA','ABAIXO',
    'PERTO','LONGE','JUNTO','JUNTA','SEPARADO','SEPARADA','UNIDO','UNIDA','SOZINHO',
    'SOZINHA','ACOMPANHADO','ACOMPANHADA','SOZINHO','ACOMPANHADO','ISOLADO','ISOLADA',
    'SEGURO','SEGURA','PERIGOSO','PERIGOSA','TRANQUILO','TRANQUILA','CALMO','CALMA',
    'NERVOSO','NERVOSA','ANSIOSO','ANSIOSA','PREOCUPADO','PREOCUPADA','ALIVIADO',
    'ALIVIADA','CONTENTE','SATISFEITO','SATISFEITA','INSATISFEITO','INSATISFEITA',
    'ORGULHOSO','ORGULHOSA','HUMILDE','CONFIANTE','INSEGURO','INSEGURA','CORAJOSO',
    'CORAJOSA','MEDROSO','MEDROSA','OTIMISTA','PESSIMISTA','REALISTA','IDEALISTA',
    'LAMURIA','LAMENTO','QUEIXA','RECLAMACAO','CRITICA','ELOGIO','PIADA','BRINCADEIRA',
    'MENTIRA','VERDADE','SEGREDO','NOVIDADE','SURPRESA','CHOQUE','SUSTO','MEDO',
    'CORAGEM','FORCA','FRAQUEZA','PODER','PODEROSO','PODEROSA','FRACO','FRACA',
    'VITORIA','DERROTA','SUCESSO','FRACASSO','ERRO','ACERTO','TENTATIVA','ESFORCO',
    'TRABALHO','DESCANSO','LAZER','OCIO','PAUSA','INTERVALO','FERIAS','FOLGA',
    'SONO','SONHO','PESADELO','INSONIA','DESCANSO','PAUSA','INTERVALO','FERIAS',
    'FOCO','ATENCAO','DISTRACAO','CONCENTRACAO','MEMORIA','ESQUECIMENTO','LEMBRANCA',
    'IDEIA','PENSAMENTO','OPINIAO','JULGAMENTO','DECISAO','ESCOLHA','OPCAO','ALTERNATIVA',
    'CHANCE','OPORTUNIDADE','RISCO','PERIGO','SEGURANCA','PROTECAO','CUIDADO','ATENCAO',
    'AJUDA','APOIO','SUPORTE','AUXILIO','FAVOR','PEDIDO','ORDEM','COMANDO','PEDIDO',
    'CONVITE','ACEITE','RECUSA','PERMISSAO','PROIBICAO','LIBERDADE','PRISAO','CADEIA',
    'CASA','ESCOLA','TRABALHO','IGREJA','HOSPITAL','BANCO','MERCADO','LOJA','PADARIA',
    'FARMACIA','POSTO','DELEGACIA','PREFEITURA','FORUM','TRIBUNAL','CARTORIO','CORREIOS',
    'MUSEU','BIBLIOTECA','TEATRO','CINEMA','ESTADIO','GINASIO','ACADEMIA','CLUBE',
    'HOTEL','POUSADA','HOSTEL','RESTAURANTE','BAR','LANCHONETE','CAFETERIA','PADARIA',
    'SUPERMERCADO','HIPERMERCADO','SHOPPING','FEIRA','SACOLAO','ACOUGUE','PEIXARIA',
    'LIVRARIA','PAPELARIA','LOJA','ROUPA','CALCADO','ELETRONICO','MOVEIS','DECORACAO'
];

const CORE_WORDS = [
    ...WORDS_FAMILY,
    ...WORDS_COLORS,
    ...WORDS_JOBS,
    ...WORDS_BODY,
    ...WORDS_OBJECTS,
    ...WORDS_COUNTRIES,
    ...WORDS_TRAITS,
    ...WORDS_ANIMALS,
    ...WORDS_SKY,
    ...WORDS_NATURE,
    ...WORDS_GENERAL,
    ...WORDS_COMMON_EXTRA,
    ...ADJECTIVE_BASES,
    ...ADJECTIVE_FORMS,
    ...ADJECTIVE_RELATED,
    ...NOUN_COMMON
];

// ========== VERBOS DE AÇÃO (conjugação automática) ==========
const VERBS_AR = [
    'AMAR','MIAR','FUMAR','COLAR','FALAR','ANDAR','PULAR','CANTAR','DANCAR',
    'OLHAR','CHAMAR','MANDAR','MORAR','CUIDAR','AJUDAR','ESPERAR','GANHAR',
    'JOGAR','PEGAR','LEVAR','SOLTAR','JUNTAR','COMPRAR','PAGAR','CHORAR',
    'CHEGAR','VOLTAR','ENTRAR','FECHAR','FICAR','COMECAR','TERMINAR',
    'ESTUDAR','TRABALHAR','BRINCAR','GOSTAR','PENSAR','LEMBRAR','PASSAR',
    'USAR','TOCAR','PROCURAR','ENCONTRAR','PRECISAR','ACORDAR','DEITAR',
    'LEVANTAR','CAMINHAR','VIAJAR','SONHAR','NAMORAR','BEIJAR','ABRACAR',
    'GRITAR','CHUTAR','PINTAR','LIMPAR','LAVAR','SECAR','DOBRAR','GUARDAR',
    'TIRAR','COLOCAR','MOSTRAR','CONTAR','PARAR','TENTAR','ACEITAR',
    'AVISAR','MARCAR','NOTAR','GIRAR','VIRAR','MUDAR','TROCAR','PREPARAR',
    'ARRUMAR','QUEBRAR','CORTAR','SEPARAR','EMPURRAR','PUXAR','CARREGAR',
    'TOMAR','ORAR','MOLAR','NADAR','SURFAR','PEDALAR','DIRIGIR','VOAR',
    'NADAR','SALVAR','CURAR','TRATAR','OPERAR','CONSULTAR','EXAMINAR',
    'ADOTAR','ADORAR','CRIAR','EDUCAR','LAMURIAR','LAMENTAR','QUEIXAR','RECLAMAR',
    'SUSPIRAR','SOLUCAR','GEMER','CHORAR','GRITAR',
    'ENSINAR','APRENDER','EXPLICAR','PERGUNTAR','RESPONDER','CONVERSAR',
    'CONVERSAR','DISCUTIR','BRIGAR','GRitar','SORRIR','CHORAR','GRITAR',
    'COZINHAR','ASSAR','FRITAR','FERVER','MISTURAR','TEMPERAR','PROVAR',
    'SERVIR','CONVIDAR','VISITAS','VISITAR','RECEBER','ENVIAR','MANDAR',
    'LIGAR','DESLIGAR','ABRIR','FECHAR','LIGAR','CHAMAR','AVISAR','INFORMAR',
    'DECIDIR','ESCOLHER','PREFERIR','ACEITAR','RECUSAR','PERMITIR','PROIBIR',
    'CRIAR','INVENTAR','CONSTRUIR','MONTAR','DESMONTAR','CONSERTAR','CONSERTAR',
    'LIMPAR','ARRUMA','ARRUMAR','ORGANIZAR','PLANEJAR','AGENDAR','MARCAR',
    'COMECA','COMECAR','CONTINUAR','TERMINAR','FINALIZAR','CONCLUIR','PARAR',
    'ESPERAR','ADIANTAR','ATRASAR','CHEGAR','SAIR','ENTRAR','VOLTAR','FICAR',
    'MORAR','MUDAR','VIAJAR','PASSEAR','CORRER','CAMINHAR','MARCHAR','PULAR',
    'DANCAR','CANTAR','TOCAR','OUVIR','ASSISTIR','LER','ESCREVER','DESENHAR',
    'PINTAR','FOTOGRAFAR','FILMAR','GRAVAR','EDITAR','PUBLICAR','COMPARTILHAR',
    'BAIXAR','ENVIAR','RECEBER','APAGAR','SALVAR','COPIAR','COLAR','CORTAR',
    'PESQUISAR','BUSCAR','PROCURAR','ACHAR','ENCONTRAR','PERDER','ACHAR',
    'COMPRAR','VENDER','ALUGAR','EMPRESTAR','DEVOLVER','PAGAR','COBRAR','CUSTAR',
    'TRABALHAR','ESTUDAR','ENSINAR','APRENDER','TREINAR','PRATICAR','ENSINAR',
    'CUIDAR','TRATAR','CURAR','PROTEGER','DEFENDER','ATACAR','LUTAR','BRIGAR',
    'AMAR','ODIAR','GOSTAR','ADORAR','DETESTAR','TEMER','ESPERAR','DESEJAR',
    'SONHAR','IMAGINAR','LEMBRAR','ESQUECER','PENSAR','REFLETIR','DECIDIR',
    'ACORDAR','DORMIR','DESCANSA','DESCANSAR','RELAXAR','ESTICAR','EXERCITAR',
    'ALIMENTAR','NUTRIR','BEBER','COMER','LANCHAR','JANTAR','CAFEZAR','TOMAR'
];

const VERBS_ER = [
    'COMER','BEBER','CORRER','VIVER','PERDER','VENDER','RECEBER','MEXER',
    'DESCER','ESCONDER','APRENDER','ENTENDER','NASCER','CRESCER','PARECER',
    'CONHECER','APARECER','MERECER','ROER','ESCREVER','DOER','LER','VER',
    'FAZER','DIZER','TRAZER','QUERER','PODER','SABER','CABER','HAVER',
    'DEVIR','PRAZER','JAZER','AQUECER','ESFRIAR','RESOLVER','DEVOLVER',
    'ENVOLVER','DESENVOLVER','PROMETER','COMETER','METER',
    'REMETER','SOMETER','SOFRER','OFERECER','ESCOLHER','COLHER',
    'ABSORVER','DISSOLVER','MOVER','REMOVER','PROMOVER','COMMOVER',
    'PERCORRER','SOCORRER','OCORRER','RECORRER','DECORRER','REVIVER',
    'SOBREVIVER','CONVIVER','DESCREVER','INSCREVER','SUBSCREVER',
    'RELER','ELEGER','PROTEGER','BATER','ABATER','REBATER','COMBATER','DEBATER',
    'GEMER','TEMER','ESCONDER','PRENDER','DEPENDER','SURPREENDER','ENTENDER'
];

const VERBS_IR = [
    'PARTIR','SAIR','ABRIR','SENTIR','DORMIR','SUBIR','CAIR','OUVIR',
    'PEDIR','VESTIR','SERVIR','SEGUIR','SORRIR','ASSISTIR','EXISTIR',
    'INSISTIR','DESISTIR','PREFERIR','REFERIR','FERIR','MENTIR',
    'INVESTIR','DIVERTIR','ADVERTIR','CONVERTER','INVERTER','PERVERTIR',
    'CONSTRUIR','INSTRUIR','DESTRUIR','CONDUZIR','PRODUZIR','TRADUZIR',
    'REDUZIR','SEDUZIR','INTRODUZIR','REPRODUZIR','INCLUIR','EXCLUIR',
    'CONCLUIR','DISTRIBUIR','CONTRIBUIR','ATRIBUIR','SUBSTITUIR','CONSTITUIR',
    'IR','VIR','RI','CUMPRIR','ATINGIR','FINGIR','TINGIR','UNGIR','JUNGIR',
    'DIRIGIR','CORRIGIR','EXIGIR','PROIBIR','EXIBIR','INIBIR','COIBIR',
    'DEFINIR','FINIR','COBRIR','DESCOBRIR','RECOBRIR','SOFRIR',
    'DESMENTIR','PRESSENTIR','CONSENTIR','RESSENTIR','REPARTIR',
    'COMPARTIR','MEDIR','LATIR','LATIR','RUIR','FLUIR','CONCLUIR'
];

function conjugateAR(verb) {
    const v = stripAccents(verb);
    if (!v.endsWith('AR') || v.length < 4) return [];
    const s = v.slice(0, -2);
    return [
        v,
        s+'O', s+'AS', s+'A', s+'AMOS', s+'AIS', s+'AM',
        s+'EI', s+'ASTE', s+'OU', s+'AMOS', s+'ASTES', s+'ARAM',
        s+'AVA', s+'AVAS', s+'AVA', s+'AVAMOS', s+'AVEIS', s+'AVAM',
        s+'AREI', s+'ARAS', s+'ARA', s+'AREMOS', s+'AREIS', s+'ARAO',
        s+'ARIA', s+'ARIAS', s+'ARIA', s+'ARIAMOS', s+'ARIEIS', s+'ARIAM',
        s+'E', s+'ES', s+'E', s+'EMOS', s+'EIS', s+'EM',
        s+'ASSE', s+'ASSES', s+'ASSE', s+'ASSEMOS', s+'ASSEIS', s+'ASSEM',
        s+'ANDO', s+'ADO', s+'ADA', s+'ADOS', s+'ADAS',
        s+'A', s+'AI', s+'E', s+'EM'
    ];
}

function conjugateER(verb) {
    const v = stripAccents(verb);
    if (!v.endsWith('ER') || v.length < 4) return [];
    const s = v.slice(0, -2);
    return [
        v,
        s+'O', s+'ES', s+'E', s+'EMOS', s+'EIS', s+'EM',
        s+'I', s+'ESTE', s+'EU', s+'EMOS', s+'ESTES', s+'ERAM',
        s+'IA', s+'IAS', s+'IA', s+'IAMOS', s+'IEIS', s+'IAM',
        s+'EREI', s+'ERAS', s+'ERA', s+'EREMOS', s+'EREIS', s+'ERAO',
        s+'ERIA', s+'ERIAS', s+'ERIA', s+'ERIAMOS', s+'ERIEIS', s+'ERIAM',
        s+'A', s+'AS', s+'A', s+'AMOS', s+'AIS', s+'AM',
        s+'ESSE', s+'ESSES', s+'ESSE', s+'ESSEMOS', s+'ESSEIS', s+'ESSEM',
        s+'ENDO', s+'IDO', s+'IDA', s+'IDOS', s+'IDAS',
        s+'E', s+'EI', s+'A', s+'AM'
    ];
}

function conjugateIR(verb) {
    const v = stripAccents(verb);
    if (!v.endsWith('IR') || v.length < 4) return [];
    const s = v.slice(0, -2);
    return [
        v,
        s+'O', s+'ES', s+'E', s+'IMOS', s+'IS', s+'EM',
        s+'I', s+'ISTE', s+'IU', s+'IMOS', s+'ISTES', s+'IRAM',
        s+'IA', s+'IAS', s+'IA', s+'IAMOS', s+'IEIS', s+'IAM',
        s+'IREI', s+'IRAS', s+'IRA', s+'IREMOS', s+'IREIS', s+'IRAO',
        s+'IRIA', s+'IRIAS', s+'IRIA', s+'IRIAMOS', s+'IRIEIS', s+'IRIAM',
        s+'A', s+'AS', s+'A', s+'AMOS', s+'AIS', s+'AM',
        s+'ISSE', s+'ISSES', s+'ISSE', s+'ISSEMOS', s+'ISSEIS', s+'ISSEM',
        s+'INDO', s+'IDO', s+'IDA', s+'IDOS', s+'IDAS',
        s+'E', s+'I', s+'A', s+'AM'
    ];
}

const IRREGULAR_FORMS = [
    'SER','SOU','ES','E','SOMOS','SOIS','SAO','FUI','FOSTE','FOI','FOMOS','FORAM',
    'ERA','ERAS','ERA','ERAMOS','EREIS','ERAM','SEJA','SEJAS','SEJAMOS','SEJAM',
    'SIDO','SENDO','FOR','FORES','FORMOS','FOREM',
    'ESTAR','ESTOU','ESTAS','ESTA','ESTAMOS','ESTAO','ESTIVE','ESTIVESTE','ESTEVE',
    'ESTIVEMOS','ESTIVERAM','ESTAVA','ESTAVAS','ESTAVAM','ESTEJA','ESTANDO','ESTADO',
    'TER','TENHO','TENS','TEM','TEMOS','TEM','TIVE','TIVESTE','TEVE','TIVEMOS','TIVERAM',
    'TINHA','TINHAS','TINHAM','TENHA','TENHAS','TENHAM','TENDO','TIDO',
    'IR','VOU','VAIS','VAI','VAMOS','VAO','FUI','FOSTE','FOI','FOMOS','FORAM',
    'IA','IAS','IAM','VA','VADES','VAO','INDO','IDO',
    'VIR','VENHO','VENS','VEM','VIMOS','VEM','VIM','VIESTE','VEIO','VIEMOS','VIERAM',
    'VINHA','VINHAS','VINHAM','VENHA','VENHAS','VENHAM','VINDO',
    'FAZER','FACO','FAZES','FAZ','FAZEMOS','FAZEM','FIZ','FIZESTE','FEZ','FIZEMOS','FIZERAM',
    'FAZIA','FAZIAS','FAZIAM','FACA','FACAS','FACAM','FAZENDO','FEITO',
    'DIZER','DIGO','DIZES','DIZ','DIZEMOS','DIZEM','DISSE','DISSESTE','DISSE','DISSEMOS','DISSERAM',
    'DIZIA','DIZIAS','DIZIAM','DIGA','DIGAS','DIGAM','DIZENDO','DITO',
    'TRAZER','TRAGO','TRAZES','TRAZ','TRAZEMOS','TRAZEM','TROUXE','TROUXESTE','TROUXE','TROUXEMOS',
    'TRAZIA','TRAGA','TRAGAS','TRAGAM','TRAZENDO','TRAZIDO',
    'PODER','POSSO','PODES','PODE','PODEMOS','PODEM','PUDE','PUDESTE','PODE','PUDEMOS','PUDERAM',
    'PODIA','PODIAS','PODIAM','POSSA','POSSAS','POSSAM','PODENDO','PODIDO',
    'QUERER','QUERO','QUERES','QUER','QUEREMOS','QUEREM','QUIS','QUISESTE','QUIS','QUISEMOS','QUISERAM',
    'QUERIA','QUERIAS','QUERIAM','QUEIRA','QUEIRAS','QUEIRAM','QUERENDO','QUERIDO',
    'SABER','SEI','SABES','SABE','SABEMOS','SABEM','SOUBE','SOUBESTE','SOUBE','SOUBEMOS','SOUBERAM',
    'SABIA','SABIAS','SABIAM','SAIBA','SAIBAS','SAIBAM','SABENDO','SABIDO',
    'VER','VEJO','VES','VE','VEMOS','VEEM','VI','VISTE','VIU','VIMOS','VIRAM',
    'VIA','VIAS','VIAM','VEJA','VEJAS','VEJAM','VENDO','VISTO',
    'LER','LEIO','LES','LE','LEMOS','LEEM','LI','LESTE','LEU','LEMOS','LERAM',
    'LIA','LIAS','LIAM','LEIA','LEIAS','LEIAM','LENDO','LIDO',
    'DAR','DOU','DAS','DA','DAMOS','DAO','DEI','DESTE','DEU','DEMOS','DERAM',
    'DAVA','DAVAS','DAVAM','DE','DES','DEM','DANDO','DADO','DADA','DADOS','DADAS',
    'POR','PONHO','POES','POE','POMOS','POEM','PUS','PUSESTE','POS','PUSEMOS','PUSERAM',
    'PUNHA','PUNHAS','PUNHAM','PONHA','PONHAS','PONHAM','PONDO','POSTO',
    'HAVER','HEI','HAS','HA','HAVEMOS','HAO','HOUVE','HOUVESTE','HOUVE','HOUVEMOS','HOUVERAM',
    'HAVIA','HAVIAS','HAVIAM','HAJA','HAJAS','HAJAM','HAVENDO','HAVIDO',
    'MIAR','MIO','MIAS','MIA','MIAMOS','MIAM','MIEI','MIOU','MIARAM','MIAVA','MIANDO','MIADO',
    'TOMAR','TOMO','TOMAS','TOMA','TOMAMOS','TOMAM','TOMEI','TOMOU','TOMARAM','TOMANDO','TOMADO',
    'ORAR','ORO','ORAS','ORA','ORAMOS','ORAM','OREI','OROU','ORARAM','ORE','ORES','OREM','ORANDO','ORADO',
    'CAIR','CAIO','CAIS','CAI','CAIMOS','CAEM','CAIU','CAIRAM','CAIA','CAINDO','CAIDO',
    'SAIR','SAIO','SAIS','SAI','SAIMOS','SAEM','SAIU','SAIRAM','SAIA','SAINDO','SAIDO',
    'OUVIR','OUCO','OUVES','OUVE','OUVIMOS','OUVEM','OUVI','OUVIU','OUVIA','OUCA','OUVINDO','OUVIDO',
    'PEDIR','PECO','PEDES','PEDE','PEDIMOS','PEDEM','PEDI','PEDIU','PEDIA','PECA','PEDINDO','PEDIDO',
    'DORMIR','DURMO','DORMES','DORME','DORMIMOS','DORMEM','DORMI','DORMIU','DORMIA','DORMINDO','DORMIDO',
    'SENTIR','SINTO','SENTES','SENTE','SENTIMOS','SENTEM','SENTI','SENTIU','SENTIA','SENTINDO','SENTIDO',
    'COMER','COMO','COMES','COME','COMEMOS','COMEM','COMI','COMEU','COMERAM','COMENDO','COMIDO',
    'BEBER','BEBO','BEBES','BEBE','BEBEMOS','BEBEM','BEBI','BEBEU','BEBERAM','BEBENDO','BEBIDO',
    'CORRER','CORRO','CORRES','CORRE','CORREMOS','CORREM','CORRI','CORREU','CORRERAM','CORRENDO','CORRIDO',
    'VIVER','VIVO','VIVES','VIVE','VIVEMOS','VIVEM','VIVI','VIVEU','VIVERAM','VIVENDO','VIVIDO',
    'AMAR','AMO','AMAS','AMA','AMAMOS','AMAM','AMEI','AMOU','AMARAM','AMANDO','AMADO','AME','AMEM',
    'FUMAR','FUMO','FUMAS','FUMA','FUMEI','FUMOU','FUMANDO','FUMADO',
    'OLE','DOR','DORES','NATO','NATA','NATOS','NATAS','NETO','NETA','NETOS','NETAS',
    // miar (família completa)
    'MIAR','MIO','MIAS','MIA','MIAMOS','MIAM','MIEI','MIASTE','MIOU','MIARAM',
    'MIAVA','MIAVAS','MIAVAM','MIE','MIES','MIEM','MIANDO','MIADO','MIADA','MIADOS','MIADAS',
    // sonhar / sono / sonho
    'SONHAR','SONHO','SONHAS','SONHA','SONHAMOS','SONHAM','SONHEI','SONHASTE','SONHOU','SONHARAM',
    'SONHAVA','SONHAVAS','SONHAVAM','SONHE','SONHES','SONHEM','SONHANDO','SONHADO','SONHADA',
    'SONO','SONOS','SONHOS','SONHECO','SONOLENTO','SONOLENTA','INSONIA','PESADELO',
    // amar / amor (família completa)
    'AMOR','AMORES','AMOROSO','AMOROSA','AMORAVEL','AMAVEL','AMADA','AMADAS','AMADOS',
    'AMANTE','AMANTES','AMIZADE','AMIGO','AMIGA','AMIGOS','AMIGAS','AMANDO',
    'NAMORO','NAMORAR','NAMORA','NAMORO','NAMOROU','BEIJO','BEIJAR','BEIJOS'
];

/** Famílias: se tem o substantivo/verbo, entram todas as formas relacionadas */
const WORD_FAMILIES = {
    MIAR: ['MIAR','MIO','MIAS','MIA','MIAMOS','MIAM','MIEI','MIASTE','MIOU','MIARAM',
           'MIAVA','MIAVAS','MIAVAM','MIE','MIES','MIEM','MIANDO','MIADO','MIADA','MIADOS','MIADAS','MIAU'],
    AMAR: ['AMAR','AMO','AMAS','AMA','AMAMOS','AMAIS','AMAM','AMEI','AMASTE','AMOU','AMARAM',
           'AMAVA','AMAVAS','AMAVAM','AME','AMES','AMEM','AMANDO','AMADO','AMADA','AMADOS','AMADAS',
           'AMOR','AMORES','AMOROSO','AMOROSA','AMORAVEL','AMAVEL','AMANTE','AMANTES'],
    SONHAR: ['SONHAR','SONHO','SONHAS','SONHA','SONHAMOS','SONHAM','SONHEI','SONHASTE','SONHOU','SONHARAM',
             'SONHAVA','SONHAVAS','SONHAVAM','SONHE','SONHES','SONHEM','SONHANDO','SONHADO','SONHADA',
             'SONHADOS','SONHADAS','SONO','SONOS','SONHOS','SONOLENTO','SONOLENTA','INSONIA','PESADELO'],
    DORMIR: ['DORMIR','DURMO','DORMES','DORME','DORMIMOS','DORMEM','DORMI','DORMISTE','DORMIU','DORMIRAM',
             'DORMIA','DORMIAS','DORMIAM','DURMA','DURMAS','DURMAM','DORMINDO','DORMIDO','DORMIDA','SONO'],
    AMOR: ['AMOR','AMORES','AMAR','AMO','AMA','AMAS','AMAM','AMEI','AMOU','AMADO','AMADA','AMANDO','AMAVEL'],
    SONHO: ['SONHO','SONHOS','SONHAR','SONHA','SONHAS','SONHAM','SONHEI','SONHOU','SONHADO','SONHANDO','SONO'],
    SONO: ['SONO','SONOS','SONHAR','SONHO','SONHA','DORMIR','DORME','DORMI','DORMIU','DORMIDO'],
    MIAU: ['MIAU','MIAR','MIA','MIO','MIOU','MIADO','MIADA','MIANDO'],
    GATO: ['GATO','GATA','GATOS','GATAS','GATINHO','GATINHA','MIAU','MIAR','MIA','MIOU','MIADO'],
    FUMO: ['FUMO','FUMAR','FUMA','FUMAS','FUMAM','FUMEI','FUMOU','FUMADO','FUMANDO','CIGARRO'],
    MOLA: ['MOLA','MOLAS','MOLAR','MOLO','MOLAS','MOLEI','MOLOU','MOLADO','MOLANDO','ELASTICO'],
    TOMAR: ['TOMAR','TOMO','TOMAS','TOMA','TOMAM','TOMEI','TOMOU','TOMADO','TOMANDO','TOME'],
    ORAR: ['ORAR','ORO','ORAS','ORA','ORAM','OREI','OROU','ORADO','ORANDO','ORE','ORES','OREM','ORACAO'],
    DAR: ['DAR','DOU','DAS','DA','DAMOS','DAO','DEI','DEU','DADO','DANDO','DE','DEM'],
    BAR: ['BAR','BARES','BARMAN','BALCAO'],
    DOR: ['DOR','DORES','DOER','DOI','DOEU','DOENDO','DOIDO','DOIDA'],
    COR: ['COR','CORES','COLORIDO','COLORIDA','COLORIR','PINTAR','TINTA'],
    RIO: ['RIO','RIOS','RIACHO','RIR','RISO','RISOS','RISADA'],
    RIR: ['RIR','RIO','RIS','RI','RIMOS','RIEM','RI','RIU','RIRAM','RINDO','RIDO','RISO','RISOS','RISADA'],
    CHORAR: ['CHORAR','CHORO','CHORAS','CHORA','CHORAM','CHOREI','CHOROU','CHORADO','CHORANDO','CHORO','LAGRIMA'],
    COMER: ['COMER','COMO','COMES','COME','COMEM','COMI','COMEU','COMIDO','COMENDO','COMIDA'],
    BEBER: ['BEBER','BEBO','BEBES','BEBE','BEBEM','BEBI','BEBEU','BEBIDO','BEBENDO','BEBIDA'],
    FALAR: ['FALAR','FALO','FALAS','FALA','FALAM','FALEI','FALOU','FALADO','FALANDO','FALA','FALAS'],
    ANDAR: ['ANDAR','ANDO','ANDAS','ANDA','ANDAM','ANDEI','ANDOU','ANDADO','ANDANDO','ANDAR'],
    JOGAR: ['JOGAR','JOGO','JOGAS','JOGA','JOGAM','JOGUEI','JOGOU','JOGADO','JOGANDO','JOGO','JOGOS'],
    CANTAR: ['CANTAR','CANTO','CANTAS','CANTA','CANTAM','CANTEI','CANTOU','CANTADO','CANTANDO','CANTO','CANCAO'],
    DANCAR: ['DANCAR','DANCO','DANCAS','DANCA','DANCAM','DANCEI','DANCOU','DANCADO','DANCANDO','DANCA'],
    OLHAR: ['OLHAR','OLHO','OLHAS','OLHA','OLHAM','OLHEI','OLHOU','OLHADO','OLHANDO','OLHO','OLHOS'],
    MORAR: ['MORAR','MORO','MORAS','MORA','MORAM','MOREI','MOROU','MORADO','MORANDO','MORADIA','CASA'],
    TRABALHAR: ['TRABALHAR','TRABALHO','TRABALHA','TRABALHEI','TRABALHOU','TRABALHANDO','TRABALHADO'],
    ESTUDAR: ['ESTUDAR','ESTUDO','ESTUDAS','ESTUDA','ESTUDAM','ESTUDEI','ESTUDOU','ESTUDANDO','ESTUDADO'],
    BRINCAR: ['BRINCAR','BRINCO','BRINCAS','BRINCA','BRINCAM','BRINQUEI','BRINCOU','BRINCANDO','BRINCADO','BRINQUEDO'],
    CORRER: ['CORRER','CORRO','CORRES','CORRE','CORREM','CORRI','CORREU','CORRIDO','CORRENDO','CORRIDA'],
    PULAR: ['PULAR','PULO','PULAS','PULA','PULAM','PULEI','PULOU','PULADO','PULANDO','PULO'],
    NADAR: ['NADAR','NADO','NADAS','NADA','NADAM','NADEI','NADOU','NADADO','NADANDO','NADO'],
    LER: ['LER','LEIO','LES','LE','LEMOS','LEEM','LI','LEU','LIDO','LENDO','LEITURA','LIVRO'],
    ESCREVER: ['ESCREVER','ESCREVO','ESCREVES','ESCREVE','ESCREVI','ESCREVEU','ESCRITO','ESCREVENDO'],
    VER: ['VER','VEJO','VES','VE','VEMOS','VI','VIU','VISTO','VENDO','VISAO','OLHO'],
    OUVIR: ['OUVIR','OUCO','OUVES','OUVE','OUVI','OUVIU','OUVIDO','OUVINDO','OUVIDO','SOM'],
    SENTIR: ['SENTIR','SINTO','SENTES','SENTE','SENTI','SENTIU','SENTIDO','SENTINDO','SENTIMENTO'],
    PENSAR: ['PENSAR','PENSO','PENSAS','PENSA','PENSAM','PENSEI','PENSOU','PENSADO','PENSANDO','PENSAMENTO'],
    GOSTAR: ['GOSTAR','GOSTO','GOSTAS','GOSTA','GOSTAM','GOSTEI','GOSTOU','GOSTADO','GOSTANDO','GOSTO'],
    QUERER: ['QUERER','QUERO','QUERES','QUER','QUEREM','QUIS','QUERIA','QUERIDO','QUERENDO'],
    PODER: ['PODER','POSSO','PODES','PODE','PODEM','PUDE','PODIA','PODIDO','PODENDO'],
    SABER: ['SABER','SEI','SABES','SABE','SABEM','SOUBE','SABIA','SABIDO','SABENDO','SABEDORIA'],
    FAZER: ['FAZER','FACO','FAZES','FAZ','FAZEM','FIZ','FEZ','FEITO','FAZENDO'],
    DIZER: ['DIZER','DIGO','DIZES','DIZ','DIZEM','DISSE','DITO','DIZENDO'],
    IR: ['IR','VOU','VAIS','VAI','VAMOS','VAO','FUI','FOI','IDO','INDO','IDA'],
    VIR: ['VIR','VENHO','VENS','VEM','VIM','VEIO','VINDO','VINDO'],
    TER: ['TER','TENHO','TENS','TEM','TEMOS','TIVE','TEVE','TIDO','TENDO'],
    SER: ['SER','SOU','ES','E','SOMOS','SAO','FUI','FOI','SIDO','SENDO'],
    ESTAR: ['ESTAR','ESTOU','ESTAS','ESTA','ESTAMOS','ESTAO','ESTIVE','ESTEVE','ESTADO','ESTANDO'],
    BEIJAR: ['BEIJAR','BEIJO','BEIJAS','BEIJA','BEIJAM','BEIJEI','BEIJOU','BEIJADO','BEIJANDO','BEIJO','BEIJOS'],
    ABRACAR: ['ABRACAR','ABRACO','ABRACAS','ABRACA','ABRACAM','ABRACEI','ABRACOU','ABRACADO','ABRACANDO','ABRACO'],
    NAMORAR: ['NAMORAR','NAMORO','NAMORAS','NAMORA','NAMORAM','NAMOREI','NAMOROU','NAMORADO','NAMORANDO','NAMORO'],

    // bater (bata, bate, bati, bateu, batido…)
    BATER: ['BATER','BATO','BATES','BATE','BATEMOS','BATEM','BATI','BATESTE','BATEU','BATEMOS','BATERAM',
            'BATIA','BATIAS','BATIAM','BATA','BATAS','BATAM','BATENDO','BATIDO','BATIDA','BATIDOS','BATIDAS',
            'BATIDA','BATIDAS','BATEDEIRA','BATERIA','BATENTE','BATEDOR','BATEDORA','ABATER','REBATER',
            'COMBATER','DEBATER','BATEBOCA','BATIDA','PULSAR','PULSO'],
    BATE: ['BATE','BATER','BATO','BATES','BATI','BATEU','BATA','BATIDO','BATENDO','BATIDA'],
    BATA: ['BATA','BATAS','BATER','BATE','BATO','BATI','BATEU','BATIDO','BATENDO'],
    BATIDO: ['BATIDO','BATIDA','BATIDOS','BATIDAS','BATER','BATE','BATEU','BATENDO'],

    // latir (late, latiu, latido…) + cão
    LATIR: ['LATIR','LATO','LATES','LATE','LATIMOS','LATEM','LATI','LATISTE','LATIU','LATIRAM',
            'LATIA','LATIAS','LATIAM','LATA','LATAS','LATAM','LATINDO','LATIDO','LATIDA','LATIDOS','LATIDAS',
            'LATIDO','AUAU','CAO','CAES','CACHORRO','CACHORRA','CACHORRINHO','VIRA','LATA'],
    LATE: ['LATE','LATIR','LATO','LATES','LATI','LATIU','LATA','LATIDO','LATINDO','CAO','AUAU'],
    CAO: ['CAO','CAES','CACHORRO','CACHORRA','CACHORROS','LATIR','LATE','LATIU','LATIDO','AUAU','LATINDO'],
    CACHORRO: ['CACHORRO','CACHORRA','CACHORROS','CACHORRINHO','CAO','LATIR','LATE','LATIDO','AUAU'],

    // eu / possessivos / pronomes pessoais
    EU: ['EU','MEU','MINHA','MEUS','MINHAS','MIM','COMIGO','ME','MIGO',
         'TU','TEU','TUA','TEUS','TUAS','TI','CONTIGO','TE',
         'ELE','ELA','ELES','ELAS','SEU','SUA','SEUS','SUAS','SI','CONSIGO','LHE','LHES',
         'NOS','NOSSO','NOSSA','NOSSOS','NOSSAS','CONVOSCO','VOS',
         'VOSSO','VOSSA','VOSSOS','VOSSAS','VOCE','VOCES',
         'PROPRIO','PROPRIA','PROPRIOS','PROPRIAS','MESMO','MESMA','MESMOS','MESMAS',
         'ISTO','ISSO','AQUILO','ESTE','ESTA','ESSE','ESSA','AQUELE','AQUELA',
         'DESTE','DESTA','DESSE','DESSA','DAQUELE','DAQUELA','NESTE','NESTA','NESSE','NESSA',
         'MEU','SEU','SUA','NOSSO','VOSSO','MINHA','TEU','TUA'],
    MEU: ['MEU','MINHA','MEUS','MINHAS','EU','MIM','COMIGO','SEU','SUA','TEU','TUA','NOSSO','NOSSA'],
    MINHA: ['MINHA','MEU','MEUS','MINHAS','EU','MIM','COMIGO'],
    SEU: ['SEU','SUA','SEUS','SUAS','ELE','ELA','ELES','ELAS','VOCE','PROPRIO','PROPRIA'],
    SUA: ['SUA','SEU','SEUS','SUAS','ELA','ELE','VOCE','PROPRIA','PROPRIO'],
    TEU: ['TEU','TUA','TEUS','TUAS','TU','TI','CONTIGO'],
    TUA: ['TUA','TEU','TEUS','TUAS','TU','TI','CONTIGO'],
    NOSSO: ['NOSSO','NOSSA','NOSSOS','NOSSAS','NOS','A','GENTE'],
    NOSSA: ['NOSSA','NOSSO','NOSSOS','NOSSAS','NOS'],
    VOCE: ['VOCE','VOCES','SEU','SUA','SEUS','SUAS','LHE','LHES'],
    ELE: ['ELE','ELA','ELES','ELAS','SEU','SUA','SEUS','SUAS','LHE','LHES','SI','CONSIGO'],
    ELA: ['ELA','ELE','ELES','ELAS','SEU','SUA','SEUS','SUAS'],
    MIM: ['MIM','EU','MEU','MINHA','COMIGO','ME'],
    COMIGO: ['COMIGO','EU','MIM','MEU','MINHA'],
    CONTIGO: ['CONTIGO','TU','TI','TEU','TUA'],
    CONSIGO: ['CONSIGO','SI','SEU','SUA','ELE','ELA','VOCE'],
    PROPRIO: ['PROPRIO','PROPRIA','PROPRIOS','PROPRIAS','SEU','SUA','MEU','MINHA'],
    MESMO: ['MESMO','MESMA','MESMOS','MESMAS','PROPRIO','PROPRIA','EU','ELE'],
    ISTO: ['ISTO','ISSO','AQUILO','ESTE','ESTA','ESSE','ESSA','AQUELE','AQUELA'],
    ESTE: ['ESTE','ESTA','ESTES','ESTAS','ESSE','ESSA','AQUELE','AQUELA','ISTO','ISSO'],
    ESSE: ['ESSE','ESSA','ESSES','ESSAS','ESTE','ESTA','AQUELE','AQUELA','ISSO'],
    AQUELE: ['AQUELE','AQUELA','AQUELES','AQUELAS','ESTE','ESSE','AQUILO'],
    ADOTAR: ['ADOTAR','ADOTO','ADOTAS','ADOTA','ADOTAMOS','ADOTAM','ADOTEI','ADOTASTE','ADOTOU','ADOTARAM',
             'ADOTAVA','ADOTE','ADOTES','ADOTEM','ADOTANDO','ADOTADO','ADOTADA','ADOTADOS','ADOTADAS',
             'ADOCAO','ADOTIVO','ADOTIVA','ADOTANTE','FILHO','FILHA','CRIANCA'],
    ADOTA: ['ADOTA','ADOTAR','ADOTO','ADOTAS','ADOTEI','ADOTOU','ADOTADO','ADOTADA','ADOTANDO'],
    ADOTADO: ['ADOTADO','ADOTADA','ADOTADOS','ADOTADAS','ADOTAR','ADOTA','ADOTOU','ADOCAO'],
    PAU: ['PAU','PAUS','MADEIRA','TRONCO','GALHO','VARA','TOCO','CEPO','LENHA','BASTAO','TACO'],
    MADEIRA: ['MADEIRA','PAU','PAUS','TRONCO','GALHO','LENHA','TOCO','CEPO','FLORESTA','ARVORE'],
    NATUREZA: ['NATUREZA','TERRA','MATO','FLORESTA','ARVORE','FLOR','FOLHA','RIO','MAR','PEDRA','AREIA'],
    HONESTO: ['HONESTO','HONESTA','HONESTOS','HONESTAS','HONRA','HONRADO','HONRADA',
              'DESONESTO','DESONESTA','DESONESTOS','DESONESTAS','SINCERO','SINCERA',
              'VERDADEIRO','VERDADEIRA','LEAL','FIEL','JUSTO','JUSTA','INTEGRO','INTEGRA',
              'FRANCO','FRANCA','MENTIROSO','MENTIROSA','FALSO','FALSA','CORRUPTO','CORRUPTA',
              'VERDADE','MENTIRA','ETICA','MORAL','VIRTUDE'],
    DESONESTO: ['DESONESTO','DESONESTA','DESONESTOS','DESONESTAS','HONESTO','HONESTA',
                'MENTIROSO','MENTIROSA','FALSO','FALSA','CORRUPTO','FRAUDE','MENTIRA'],
    HONESTA: ['HONESTA','HONESTO','HONESTAS','HONESTOS','HONRA','SINCERA','LEAL','FIEL','JUSTA'],
    SINCERO: ['SINCERO','SINCERA','SINCEROS','SINCERAS','HONESTO','HONESTA','FRANCO','FRANCA','VERDADE'],
    MENTIROSO: ['MENTIROSO','MENTIROSA','MENTIROSOS','MENTIROSAS','MENTIRA','FALSO','FALSA','DESONESTO'],
    JUSTO: ['JUSTO','JUSTA','JUSTOS','JUSTAS','JUSTICA','INJUSTO','INJUSTA','HONESTO','LEAL'],
    LEAL: ['LEAL','LEAIS','LEALDADE','FIEL','FIEIS','HONESTO','HONESTA','TRAIDOR','TRAIDORA'],
    FIEL: ['FIEL','FIEIS','FIDELIDADE','LEAL','HONESTO','HONESTA','INFIEL','TRAIDOR'],
    BONITO: ['BONITO','BONITA','BONITOS','BONITAS','BELEZA','LINDO','LINDA','FEIO','FEIA','FOFO','FOFA'],
    LINDO: ['LINDO','LINDA','LINDOS','LINDAS','BELEZA','BONITO','BONITA','BELO','BELA'],
    FEIO: ['FEIO','FEIA','FEIOS','FEIAS','FEIURA','BONITO','BONITA'],
    FELIZ: ['FELIZ','FELIZES','FELICIDADE','INFELIZ','INFELIZES','ALEGRE','TRISTE','CONTENTE'],
    TRISTE: ['TRISTE','TRISTES','TRISTEZA','FELIZ','ALEGRE','LAMURIA','CHORO'],
    ALEGRE: ['ALEGRE','ALEGRES','ALEGRIA','FELIZ','TRISTE','ANIMADO','ANIMADA'],
    RICO: ['RICO','RICA','RICOS','RICAS','RIQUEZA','POBRE','POBREZA','DINHEIRO'],
    POBRE: ['POBRE','POBRES','POBREZA','RICO','RICA','HUMILDE'],
    FORTE: ['FORTE','FORTES','FORCA','FRACO','FRACA','FRAQUEZA','PODEROSO'],
    FRACO: ['FRACO','FRACA','FRACOS','FRACAS','FRAQUEZA','FORTE','FORCA'],
    NOVO: ['NOVO','NOVA','NOVOS','NOVAS','VELHO','VELHA','ANTIGO','MODERNO'],
    VELHO: ['VELHO','VELHA','VELHOS','VELHAS','IDOSO','IDOSA','NOVO','ANTIGO'],
    GRANDE: ['GRANDE','GRANDES','GRANDEZA','PEQUENO','PEQUENA','ENORME','GIGANTE'],
    PEQUENO: ['PEQUENO','PEQUENA','PEQUENOS','PEQUENAS','GRANDE','MINIMO','MINUSCULO'],
    BOM: ['BOM','BOA','BONS','BOAS','OTIMO','OTIMA','RUIM','MAU','MAUS','PESSIMO'],
    MAU: ['MAU','MAUS','RUIM','RUINS','BOM','BOA','PESSIMO','MALDADE'],
    ALTO: ['ALTO','ALTA','ALTOS','ALTAS','ALTURA','BAIXO','BAIXA','GIGANTE'],
    BAIXO: ['BAIXO','BAIXA','BAIXOS','BAIXAS','ALTO','ALTA','PEQUENO'],
    GORDO: ['GORDO','GORDA','GORDOS','GORDAS','MAGRO','MAGRA','PESADO'],
    MAGRO: ['MAGRO','MAGRA','MAGROS','MAGRAS','GORDO','GORDA','FINO','FINA'],
    CALMO: ['CALMO','CALMA','CALMOS','CALMAS','TRANQUILO','NERVOSO','SERENO'],
    BRAVO: ['BRAVO','BRAVA','BRAVOS','BRAVAS','CORAJOSO','RAIVA','NERVOSO'],
    CORAJOSO: ['CORAJOSO','CORAJOSA','CORAGEM','COVARDE','MEDROSO','OUSADO'],
    TIMIDO: ['TIMIDO','TIMIDA','TIMIDEZ','VERGONHA','INTROVERTIDO'],
    GENEROSO: ['GENEROSO','GENEROSA','EGOISTA','BONDADE','DOCE'],
    ORGULHOSO: ['ORGULHOSO','ORGULHOSA','ORGULHO','HUMILDE','VANIDOSO'],
    CARINHOSO: ['CARINHOSO','CARINHOSA','CARINHO','AMOR','DOCE','AFETO'],
    DIVERTIDO: ['DIVERTIDO','DIVERTIDA','DIVERSAO','ENGRACADO','CHATO','TEDIO'],
    CANSADO: ['CANSADO','CANSADA','CANSACO','DESCANSO','SONO'],
    LIMPO: ['LIMPO','LIMPA','LIMPEZA','SUJO','SUJA','SUJEIRA'],
    SUJO: ['SUJO','SUJA','SUJEIRA','LIMPO','LIMPA','BAGUNCA'],
    DOENTE: ['DOENTE','DOENTES','DOENCA','SAUDE','SAUDAVEL','CURA','FEBRE'],
    VIVO: ['VIVO','VIVA','VIVOS','VIVAS','VIDA','MORTO','MORTA','MORTE'],
    MORTO: ['MORTO','MORTA','MORTOS','MORTAS','MORTE','VIVO','VIVA','VIDA'],
    CASADO: ['CASADO','CASADA','CASAMENTO','SOLTEIRO','NOIVO','ESPOSA','MARIDO'],
    SOLTEIRO: ['SOLTEIRO','SOLTEIRA','CASADO','NOIVO','NAMORADO'],
    AMIGO: ['AMIGO','AMIGA','AMIGOS','AMIGAS','AMIZADE','COLEGA','VIZINHO'],
    HOMEM: ['HOMEM','HOMENS','MULHER','MULHERES','SENHOR','RAPAZ','MENINO'],
    MULHER: ['MULHER','MULHERES','HOMEM','SENHORA','MOCA','MENINA','DONA'],
    CASA: ['CASA','CASAS','LAR','SALA','QUARTO','PORTA','JANELA','TELHADO'],
    DIA: ['DIA','DIAS','NOITE','MANHA','TARDE','HOJE','ONTEM','AMANHA','SOL'],
    NOITE: ['NOITE','NOITES','DIA','LUA','ESTRELA','ESCURO','SONO'],
    AGUA: ['AGUA','MAR','RIO','LAGO','CHUVA','SEDE','BEBER','LIQUIDO'],
    FOGO: ['FOGO','FOGOS','CHAMA','BRASA','FUMACA','CALOR','QUEIMAR'],
    LAMURIA: ['LAMURIA','LAMURIAS','LAMURIAR','LAMURIO','LAMURIAS','LAMURIA','LAMURIAM',
              'LAMURIEI','LAMURIOU','LAMURIADO','LAMURIADA','LAMURIANDO','LAMENTO','LAMENTAR',
              'LAMENTA','LAMENTEI','LAMENOU','LAMENTADO','CHORO','QUEIXA','RECLAMA','PRANTO'],
    LAMURIAR: ['LAMURIAR','LAMURIO','LAMURIAS','LAMURIA','LAMURIAM','LAMURIEI','LAMURIOU',
               'LAMURIADO','LAMURIANDO','LAMURIA','LAMENTO','LAMENTAR','CHORAR','QUEIXAR'],
    LAMENTO: ['LAMENTO','LAMENTAR','LAMENTA','LAMENTEI','LAMENOU','LAMENTADO','LAMURIA','CHORO'],
    QUEIXA: ['QUEIXA','QUEIXAR','QUEIXO','QUEIXOU','QUEIXADO','RECLAMA','RECLAMAR','LAMURIA'],
    RECLAMAR: ['RECLAMAR','RECLAMO','RECLAMAS','RECLAMA','RECLAMAM','RECLAMEI','RECLAMOU',
               'RECLAMADO','RECLAMANDO','RECLAMACAO','QUEIXA','LAMURIA','LAMENTO']
};

function buildWordLists() {
    const core = new Set();
    const all = new Set();

    function addList(list, toCore) {
        list.forEach(w => {
            const n = stripAccents(w).replace(/[^A-Z]/g, '');
            if (!okWord(n)) return;
            all.add(n);
            if (toCore) core.add(n);
        });
    }

    addList(WORDS_FAMILY, true);
    addList(WORDS_COLORS, true);
    addList(WORDS_JOBS, true);
    addList(WORDS_BODY, true);
    addList(WORDS_OBJECTS, true);
    addList(WORDS_COUNTRIES, true);
    addList(WORDS_TRAITS, true);
    addList(WORDS_ANIMALS, true);
    addList(WORDS_SKY, true);
    addList(WORDS_NATURE, true);
    addList(WORDS_GENERAL, true);
    addList(WORDS_COMMON_EXTRA, true);
    addList(ADJECTIVE_BASES, true);
    addList(ADJECTIVE_FORMS, true);
    addList(ADJECTIVE_RELATED, true);
    addList(NOUN_COMMON, true);
    addList(CORE_WORDS, true);

    function addForms(forms) {
        forms.forEach(f => {
            const n = stripAccents(f).replace(/[^A-Z]/g, '');
            if (okWord(n)) all.add(n);
        });
    }

    // Irregulares de gênero
    const GENDER_IRREGULAR = {
        BOM: ['BOM','BOA','BONS','BOAS'],
        MAU: ['MAU','MA','MAUS','MAS'],
        SAO: ['SAO','SA','SAOS','SAS'],
        CAO: ['CAO','CA','CAES'],
        AO: ['AO','A','AOS','AS'],
        UM: ['UM','UMA','UNS','UMAS'],
        TODO: ['TODO','TODA','TODOS','TODAS'],
        NENHUM: ['NENHUM','NENHUMA','NENHUNS','NENHUMAS'],
        ALGUM: ['ALGUM','ALGUMA','ALGUNS','ALGUMAS'],
        MUITO: ['MUITO','MUITA','MUITOS','MUITAS'],
        POUCO: ['POUCO','POUCA','POUCOS','POUCAS'],
        OUTRO: ['OUTRO','OUTRA','OUTROS','OUTRAS'],
        MESMO: ['MESMO','MESMA','MESMOS','MESMAS'],
        PROPRIO: ['PROPRIO','PROPRIA','PROPRIOS','PROPRIAS'],
        PRIMEIRO: ['PRIMEIRO','PRIMEIRA','PRIMEIROS','PRIMEIRAS'],
        TERCEIRO: ['TERCEIRO','TERCEIRA','TERCEIROS','TERCEIRAS'],
        EUROPEU: ['EUROPEU','EUROPEIA','EUROPEUS','EUROPEIAS'],
        JUDEU: ['JUDEU','JUDIA','JUDEUS','JUDIAS'],
        CRU: ['CRU','CRUA','CRUS','CRUAS'],
        NU: ['NU','NUA','NUS','NUAS'],
        BRINCALHAO: ['BRINCALHAO','BRINCALHONA','BRINCALHOES','BRINCALHONAS'],
        CAMPEAO: ['CAMPEAO','CAMPEA','CAMPEOES','CAMPEAS'],
        ANCIAO: ['ANCIAO','ANCIA','ANCIAOS','ANCIAS'],
        ORFAO: ['ORFAO','ORFA','ORFAOS','ORFAS'],
        SOLTEIRO: ['SOLTEIRO','SOLTEIRA','SOLTEIROS','SOLTEIRAS'],
        TRABALHADOR: ['TRABALHADOR','TRABALHADORA','TRABALHADORES','TRABALHADORAS'],
        VENDEDOR: ['VENDEDOR','VENDEDORA','VENDEDORES','VENDEDORAS'],
        JOGADOR: ['JOGADOR','JOGADORA','JOGADORES','JOGADORAS'],
        VENCEDOR: ['VENCEDOR','VENCEDORA','VENCEDORES','VENCEDORAS'],
        PERDEDOR: ['PERDEDOR','PERDEDORA','PERDEDORES','PERDEDORAS'],
        PROFESSOR: ['PROFESSOR','PROFESSORA','PROFESSORES','PROFESSORAS'],
        DOUTOR: ['DOUTOR','DOUTORA','DOUTORES','DOUTORAS'],
        DIRETOR: ['DIRETOR','DIRETORA','DIRETORES','DIRETORAS'],
        TRAIDOR: ['TRAIDOR','TRAIDORA','TRAIDORES','TRAIDORAS'],
        PECADOR: ['PECADOR','PECADORA','PECADORES','PECADORAS']
    };

    function expandGender(word) {
        const w = stripAccents(word).replace(/[^A-Z]/g, '');
        if (!okWord(w)) return [];
        if (GENDER_IRREGULAR[w]) return GENDER_IRREGULAR[w].filter(okWord);

        const out = new Set([w]);
        // -oso/-osa, -ivo/-iva, -ado/-ada, -ido/-ida, -eiro/-eira, -ento/-enta
        if (/(OSO|IVO|ADO|IDO|EIRO|ENTO|ESCO|ICO|ARIO|ORIO|UDO|ADO)$/.test(w) ||
            (w.endsWith('O') && !w.endsWith('AO') && !w.endsWith('EO'))) {
            const fem = w.slice(0, -1) + 'A';
            out.add(fem);
            out.add(w + 'S');
            out.add(fem + 'S');
        } else if (w.endsWith('A') && w.length > 3 && !w.endsWith('ISTA') && !w.endsWith('EZA') && !w.endsWith('URA')) {
            const masc = w.slice(0, -1) + 'O';
            out.add(masc);
            out.add(w + 'S');
            out.add(masc + 'S');
        } else if (w.endsWith('OR')) {
            out.add(w + 'A');
            out.add(w + 'ES');
            out.add(w + 'AS');
        } else if (w.endsWith('AO') && w.length > 3) {
            out.add(w.slice(0, -2) + 'A');
            out.add(w.slice(0, -2) + 'ONA');
            out.add(w.slice(0, -2) + 'OES');
            out.add(w.slice(0, -2) + 'ONAS');
            out.add(w.slice(0, -2) + 'AES');
        } else if (w.endsWith('U') && w.length >= 3 && !w.endsWith('EU')) {
            out.add(w + 'A');
            out.add(w + 'S');
            out.add(w + 'AS');
        } else if (w.endsWith('EU')) {
            out.add(w.slice(0, -2) + 'EIA');
            out.add(w + 'S');
            out.add(w.slice(0, -2) + 'EIAS');
        } else if (w.endsWith('L')) {
            // fiel → fieis; fácil → fáceis (FACIL → FACEIS)
            if (w.endsWith('IL')) out.add(w.slice(0, -2) + 'EIS');
            else out.add(w.slice(0, -1) + 'IS');
        } else if (w.endsWith('Z')) {
            out.add(w.slice(0, -1) + 'ZES');
        } else if (w.endsWith('R') || w.endsWith('S') || w.endsWith('Z')) {
            // já plural-ish
        } else if (!w.endsWith('S') && !w.endsWith('M')) {
            out.add(w + 'S'); // alegre → alegres; feliz handled separately
        }
        if (w.endsWith('Z') && w.length >= 4) {
            // feliz → felizes
            out.add(w + 'ES');
        }
        return [...out].filter(okWord);
    }

    // Expande todos os adjetivos com M/F/plural
    ADJECTIVE_BASES.forEach(adj => {
        expandGender(adj).forEach(g => {
            all.add(g);
            core.add(g);
        });
    });
    ADJECTIVE_FORMS.forEach(adj => {
        const n = stripAccents(adj).replace(/[^A-Z]/g, '');
        if (okWord(n)) { all.add(n); core.add(n); }
        expandGender(n).forEach(g => { all.add(g); core.add(g); });
    });
    NOUN_COMMON.forEach(noun => {
        const n = stripAccents(noun).replace(/[^A-Z]/g, '');
        if (okWord(n)) { all.add(n); core.add(n); }
        expandGender(n).forEach(g => { all.add(g); core.add(g); });
    });
    Object.keys(GENDER_IRREGULAR).forEach(k => addForms(GENDER_IRREGULAR[k]));

    [...all].forEach(w => addForms(expandGender(w)));

    [...new Set(VERBS_AR)].filter(v => stripAccents(v).endsWith('AR')).forEach(v => addForms(conjugateAR(v)));
    [...new Set(VERBS_ER)].filter(v => stripAccents(v).endsWith('ER')).forEach(v => addForms(conjugateER(v)));
    [...new Set(VERBS_IR)].filter(v => stripAccents(v).endsWith('IR')).forEach(v => addForms(conjugateIR(v)));
    addForms(IRREGULAR_FORMS);

    Object.keys(WORD_FAMILIES).forEach(key => {
        addForms(WORD_FAMILIES[key]);
        WORD_FAMILIES[key].forEach(w => {
            const n = stripAccents(w).replace(/[^A-Z]/g, '');
            if (okWord(n)) {
                core.add(n); all.add(n);
                expandGender(n).forEach(g => { core.add(g); all.add(g); });
            }
        });
    });

    [
        ...WORDS_FAMILY, ...WORDS_COLORS.slice(0, 40),
        ...WORDS_NATURE.slice(0, 60),
        ...ADJECTIVE_BASES.slice(0, 80),
        ...ADJECTIVE_FORMS.slice(0, 120),
        ...NOUN_COMMON.slice(0, 80),
        'HONESTO','HONESTA','HONESTOS','HONESTAS','HONRA','HONRADO','HONRADA',
        'DESONESTO','DESONESTA','DESONESTOS','DESONESTAS','SINCERO','SINCERA',
        'MENTIROSO','MENTIROSA','JUSTO','JUSTA','LEAL','FIEL','INTEGRO','INTEGRA',
        'FRANCO','FRANCA','VERDADEIRO','VERDADEIRA','FALSO','FALSA','VERDADE','MENTIRA',
        'BRASIL','PORTUGAL','MEDICO','PROFESSOR','CABECA','OLHO','BOCA','MAO',
        'CASA','MESA','COPO','CHAVE','PAU','PAUS','MADEIRA','TRONCO','GALHO',
        'AZUL','VERDE','VERMELHO','AMARELO','PRETO','BRANCO','CAMILA','AMOR',
        'AMA','AMO','AMAR','GATO','GATA','BAR','DOR','DAR','SONO','SONHO','SONHA',
        'MIA','MIO','MIOU','MIADO','BATER','BATE','BATA','LATIR','LATE','CAO',
        'MEU','MINHA','SEU','SUA','TEU','TUA','NOSSO','NOSSA',
        'ADOTAR','ADOTA','ADOTO','ADOTEI','ADOTOU','ADOTADO','ADOTADA','ADOCAO',
        'SARDA','SARDAS','SARDENTO','SARDENTA','FLOR','ARVORE','FOLHA','RIO','MAR',
        'MATO','FLORESTA','PEDRA','AREIA','CHUVA','NUVEM','VENTO','SOL','LUA',
        'LAMURIA','LAMURIAR','LAMURIO','LAMURIEI','LAMURIOU','LAMURIADO','LAMENTO',
        'BONITO','BONITA','LINDO','LINDA','FEIO','FEIA','FELIZ','TRISTE','RICO','RICA',
        'BOM','BOA','BONS','BOAS','ALTO','ALTA','BAIXO','BAIXA','NOVO','NOVA',
        'VELHO','VELHA','GRANDE','PEQUENO','PEQUENA','FORTE','FRACO','FRACA',
        'HOMEM','MULHER','AMIGO','AMIGA','DIA','NOITE','AGUA','FOGO','COMIDA'
    ].forEach(w => {
        const n = stripAccents(w).replace(/[^A-Z]/g, '');
        if (okWord(n)) { core.add(n); all.add(n); }
    });

    return {
        CORE_WORDS: [...core],
        COMMON_WORDS: [...all],
        COUNTS: {
            nature: WORDS_NATURE.length,
            objects: WORDS_OBJECTS.length,
            animals: WORDS_ANIMALS.length,
            traits: WORDS_TRAITS.length,
            adjectives: ADJECTIVE_BASES.length + ADJECTIVE_FORMS.length,
            nouns: NOUN_COMMON.length,
            sky: WORDS_SKY.length,
            total: 0
        }
    };
}

const _lists = buildWordLists();
const CORE_WORDS_FINAL = _lists.CORE_WORDS;
const COMMON_WORDS = _lists.COMMON_WORDS;
_lists.COUNTS.total = COMMON_WORDS.length;

// Sementes do mapa: 4–5 letras usuais
const MAP_SEEDS = CORE_WORDS_FINAL.filter(w =>
    w.length >= 4 && w.length <= 5 && w !== 'CAMILA'
);

// Log útil no console (dev)
if (typeof console !== 'undefined') {
    console.info('[Wordmila] palavras no dicionário:', COMMON_WORDS.length,
        '| sementes mapa:', MAP_SEEDS.length,
        '| categorias:', _lists.COUNTS);
}
